MERGE (u:University {name: "Trường Đại học Sài Gòn", description: "Trường Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, đào tạo đa ngành từ trình độ đại học đến sau đại học với các phương thức chính quy và giáo dục thường xuyên"})

// Các trường đại học đối tác quốc tế
MERGE (p1:InternationalUniversity {name: "Đại học Khoa học Ứng dụng IMC Krems", description: "Trường đại học tại Cộng hòa Áo, đối tác liên kết đào tạo chương trình Quản trị Kinh doanh và Quản lý Thương mại Điện tử"})
MERGE (p2:InternationalUniversity {name: "Trường Đại học Quốc gia Sư Phạm Đài Loan", description: "Trường đại học tại Đài Loan, đối tác đào tạo tiếng Hoa"})
MERGE (p3:InternationalUniversity {name: "Đại học Huddersfield", description: "Trường đại học tại Vương quốc Anh, đối tác liên kết đào tạo các ngành Công nghệ thông tin, Ngôn ngữ Anh, Sư phạm Anh, Quản trị kinh doanh, Tài chính - Ngân hàng"})

// Các tổ chức quốc tế
MERGE (o1:InternationalOrganization {name: "Bộ Y tế Singapore", description: "Cơ quan chính phủ Singapore cung cấp học bổng Asian Nursing Scholarship"})
MERGE (o2:InternationalOrganization {name: "Tập đoàn Y tế Quốc gia Singapore (MOHH)", description: "Tập đoàn y tế hàng đầu Singapore cung cấp học bổng và việc làm cho sinh viên"})
MERGE (o3:InternationalOrganization {name: "Bộ Giáo dục Đài Loan", description: "Cơ quan chính phủ Đài Loan cung cấp học bổng cho sinh viên quốc tế"})
MERGE (o4:InternationalOrganization {name: "Hiệp hội Phát triển Kinh tế Văn hóa Giáo dục Đài Việt", description: "Tổ chức hợp tác giáo dục giữa Đài Loan và Việt Nam"})

// Các chương trình hợp tác quốc tế
MERGE (c1:InternationalProgram {name: "Cử nhân Quốc tế Quản trị Kinh doanh và Quản lý Thương mại Điện tử", description: "Chương trình liên kết với Đại học Khoa học Ứng dụng IMC Krems (Áo), được Bộ GD&ĐT Việt Nam phê duyệt theo QĐ số 1498/QĐ-BGDĐT"})
MERGE (c2:InternationalProgram {name: "Đào tạo tiếng Hoa (Đài Loan)", description: "Chương trình liên kết với Hiệp hội Phát triển Kinh tế Văn hóa Giáo dục Đài Việt, bao gồm Hoa ngữ giao tiếp, luyện thi TOCFL và lớp Online"})
MERGE (c3:InternationalProgram {name: "Asian Nursing Scholarship", description: "Học bổng toàn phần đào tạo Trợ lý bác sĩ tại Singapore trong 3 năm, trị giá 120.000 SGD, bao gồm sinh hoạt phí, ký túc xá và cơ hội việc làm sau tốt nghiệp"})
MERGE (c4:InternationalProgram {name: "Học bổng Đài Loan", description: "Học bổng Cử nhân hệ chính quy và vừa học vừa làm các ngành Kinh tế, Thương mại, Công nghệ tại Đài Loan với hỗ trợ học phí, ký túc xá và thực tập có lương"})
MERGE (c5:InternationalProgram {name: "Chương trình chuyển tiếp Đại học Huddersfield", description: "Liên kết đào tạo các ngành Công nghệ thông tin, Ngôn ngữ Anh, Sư phạm Anh, Quản trị kinh doanh, Tài chính - Ngân hàng"})
MERGE (c6:InternationalProgram {name: "Thạc sĩ Giảng dạy tiếng Anh (TESOL)", description: "Chương trình liên kết với Đại học Huddersfield (Anh) đào tạo Thạc sĩ TESOL"})

// Các quốc gia hợp tác
MERGE (co1:Country {name: "Áo", description: "Quốc gia châu Âu, đối tác trong chương trình liên kết đào tạo Quản trị Kinh doanh"})
MERGE (co2:Country {name: "Đài Loan", description: "Đối tác trong các chương trình đào tạo tiếng Hoa và học bổng"})
MERGE (co3:Country {name: "Singapore", description: "Quốc gia Đông Nam Á, đối tác trong chương trình học bổng y tế"})
MERGE (co4:Country {name: "Anh", description: "Quốc gia châu Âu, đối tác trong các chương trình liên kết đào tạo"})
MERGE (co5:Country {name: "Hoa Kỳ", description: "Quốc gia Bắc Mỹ, đối tác hợp tác giáo dục"})
MERGE (co6:Country {name: "Nga", description: "Quốc gia châu Âu/Á, đối tác hợp tác giáo dục"})
MERGE (co7:Country {name: "Pháp", description: "Quốc gia châu Âu, đối tác hợp tác giáo dục"})
MERGE (co8:Country {name: "Australia", description: "Quốc gia châu Đại Dương, đối tác hợp tác giáo dục"})
MERGE (co9:Country {name: "Trung Quốc", description: "Quốc gia châu Á, đối tác hợp tác giáo dục"})
MERGE (co10:Country {name: "Malaysia", description: "Quốc gia Đông Nam Á, đối tác hợp tác giáo dục"})
MERGE (co11:Country {name: "New Zealand", description: "Quốc gia châu Đại Dương, đối tác hợp tác giáo dục"})
MERGE (co12:Country {name: "Thụy Điển", description: "Quốc gia châu Âu, đối tác hợp tác giáo dục"})

// Tạo quan hệ với trường
WITH u, p1, p2, p3, o1, o2, o3, o4, c1, c2, c3, c4, c5, c6, co1, co2, co3, co4, co5, co6, co7, co8, co9, co10, co11, co12
MERGE (u)-[:hasInternationalCooperation]->(p1)
MERGE (u)-[:hasInternationalCooperation]->(p2)
MERGE (u)-[:hasInternationalCooperation]->(p3)
MERGE (u)-[:hasInternationalCooperation]->(o1)
MERGE (u)-[:hasInternationalCooperation]->(o2)
MERGE (u)-[:hasInternationalCooperation]->(o3)
MERGE (u)-[:hasInternationalCooperation]->(o4)
MERGE (u)-[:offersInternationalProgram]->(c1)
MERGE (u)-[:offersInternationalProgram]->(c2)
MERGE (u)-[:offersInternationalProgram]->(c3)
MERGE (u)-[:offersInternationalProgram]->(c4)
MERGE (u)-[:offersInternationalProgram]->(c5)
MERGE (u)-[:offersInternationalProgram]->(c6)
MERGE (u)-[:cooperatesWithCountry]->(co1)
MERGE (u)-[:cooperatesWithCountry]->(co2)
MERGE (u)-[:cooperatesWithCountry]->(co3)
MERGE (u)-[:cooperatesWithCountry]->(co4)
MERGE (u)-[:cooperatesWithCountry]->(co5)
MERGE (u)-[:cooperatesWithCountry]->(co6)
MERGE (u)-[:cooperatesWithCountry]->(co7)
MERGE (u)-[:cooperatesWithCountry]->(co8)
MERGE (u)-[:cooperatesWithCountry]->(co9)
MERGE (u)-[:cooperatesWithCountry]->(co10)
MERGE (u)-[:cooperatesWithCountry]->(co11)
MERGE (u)-[:cooperatesWithCountry]->(co12)

// Tạo quan hệ giữa các chương trình và đối tác
MERGE (c1)-[:partneredWith]->(p1)
MERGE (c2)-[:partneredWith]->(p2)
MERGE (c2)-[:partneredWith]->(o4)
MERGE (c3)-[:sponsoredBy]->(o1)
MERGE (c3)-[:sponsoredBy]->(o2)
MERGE (c4)-[:sponsoredBy]->(o3)
MERGE (c5)-[:partneredWith]->(p3)
MERGE (c6)-[:partneredWith]->(p3)

// Tạo quan hệ giữa đối tác và quốc gia
MERGE (p1)-[:locatedIn]->(co1)
MERGE (p2)-[:locatedIn]->(co2)
MERGE (o1)-[:locatedIn]->(co3)
MERGE (o2)-[:locatedIn]->(co3)
MERGE (o3)-[:locatedIn]->(co2)
MERGE (o4)-[:locatedIn]->(co2)
MERGE (p3)-[:locatedIn]->(co4)