MERGE (u:University {name: "Trường Đại học Sài Gòn", description: "Trường Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, đào tạo đa ngành từ trình độ đại học đến sau đại học với các phương thức chính quy và giáo dục thường xuyên"})

// Ban lãnh đạo
MERGE (d1:Department {name: "Đảng ủy", description: "Ban lãnh đạo chính trị của trường"})
MERGE (d2:Department {name: "Hiệu trưởng", description: "Người đứng đầu nhà trường"})
MERGE (d3:Department {name: "Phó Hiệu trưởng", description: "Các phó hiệu trưởng phụ trách các lĩnh vực khác nhau"})
MERGE (d4:Department {name: "Hội đồng trường", description: "Cơ quan quản trị cao nhất của trường"})

// Tổ chức đoàn thể
MERGE (d5:Department {name: "Công đoàn", description: "Tổ chức đại diện cho quyền lợi của cán bộ, giảng viên"})
MERGE (d6:Department {name: "Đoàn Thanh niên", description: "Tổ chức thanh niên của trường"})
MERGE (d7:Department {name: "Hội Sinh viên", description: "Tổ chức đại diện cho sinh viên"})

// Phòng ban chức năng
MERGE (d8:Department {name: "Phòng Đào tạo", description: "Phụ trách công tác đào tạo chính quy"})
MERGE (d9:Department {name: "Phòng Tổ chức - Cán bộ", description: "Quản lý nhân sự và tổ chức"})
MERGE (d10:Department {name: "Văn phòng", description: "Phụ trách hành chính tổng hợp"})
MERGE (d11:Department {name: "Phòng Kế hoạch - Tài chính", description: "Quản lý tài chính và kế hoạch phát triển"})
MERGE (d12:Department {name: "Phòng Công tác sinh viên", description: "Quản lý các hoạt động sinh viên"})
MERGE (d13:Department {name: "Phòng Quản lý khoa học", description: "Quản lý hoạt động nghiên cứu khoa học"})
MERGE (d14:Department {name: "Phòng Đào tạo sau đại học", description: "Quản lý đào tạo thạc sĩ, tiến sĩ"})
MERGE (d15:Department {name: "Phòng Thanh tra - Pháp chế", description: "Thực hiện công tác thanh tra và pháp chế"})
MERGE (d16:Department {name: "Phòng Khảo thí & Đảm bảo chất lượng", description: "Quản lý khảo thí và chất lượng đào tạo"})
MERGE (d17:Department {name: "Ban Quản lý Dự án & Xây dựng", description: "Quản lý các dự án xây dựng cơ sở vật chất"})
MERGE (d18:Department {name: "Phòng Hợp tác quốc tế & Doanh nghiệp", description: "Quản lý hợp tác quốc tế và doanh nghiệp"})
MERGE (d19:Department {name: "Phòng Thiết bị", description: "Quản lý trang thiết bị giảng dạy"})
MERGE (d20:Department {name: "Phòng Giáo dục thường xuyên", description: "Quản lý đào tạo không chính quy"})

// Các trung tâm trực thuộc
MERGE (c1:Department {name: "Trung tâm Khảo thí", description: "Tổ chức các kỳ thi và đánh giá"})
MERGE (c2:Department {name: "Trung tâm Đào tạo quốc tế", description: "Đào tạo các chương trình quốc tế"})
MERGE (c3:Department {name: "Trung tâm Hỗ trợ sinh viên", description: "Hỗ trợ toàn diện cho sinh viên"})
MERGE (c4:Department {name: "Trung tâm Học liệu", description: "Quản lý tài liệu học tập"})
MERGE (c5:Department {name: "Trung tâm Công nghệ thông tin", description: "Quản lý hệ thống CNTT của trường"})
MERGE (c6:Department {name: "Trung tâm Ngoại ngữ", description: "Đào tạo và bồi dưỡng ngoại ngữ"})
MERGE (c7:Department {name: "Trung tâm Tuyển sinh & Truyền thông", description: "Tuyển sinh và truyền thông đại chúng"})
MERGE (c8:Department {name: "Trung tâm Ký túc xá", description: "Quản lý ký túc xá sinh viên"})
MERGE (c9:Department {name: "Trạm Y tế", description: "Chăm sóc sức khỏe cho cán bộ và sinh viên"})

// Các khoa chuyên môn
MERGE (f1:Faculty {name: "Khoa Giáo dục Mầm non", description: "Đào tạo giáo viên mầm non"})
MERGE (f2:Faculty {name: "Khoa Giáo dục Tiểu học", description: "Đào tạo giáo viên tiểu học"})
MERGE (f3:Faculty {name: "Khoa Sư phạm Khoa học Xã hội", description: "Đào tạo giáo viên các môn xã hội"})
MERGE (f4:Faculty {name: "Khoa Sư phạm Khoa học Tự nhiên", description: "Đào tạo giáo viên các môn tự nhiên"})
MERGE (f5:Faculty {name: "Khoa Giáo dục", description: "Đào tạo các chuyên ngành giáo dục"})
MERGE (f6:Faculty {name: "Khoa Nghệ thuật", description: "Đào tạo các ngành nghệ thuật"})
MERGE (f7:Faculty {name: "Khoa Ngoại ngữ", description: "Đào tạo ngoại ngữ và sư phạm ngoại ngữ"})
MERGE (f8:Faculty {name: "Khoa Thư viện - Văn phòng", description: "Đào tạo nghiệp vụ thư viện và văn phòng"})
MERGE (f9:Faculty {name: "Khoa Khoa học Môi trường", description: "Đào tạo về khoa học môi trường"})
MERGE (f10:Faculty {name: "Khoa Công nghệ Thông tin", description: "Đào tạo CNTT và ứng dụng"})
MERGE (f11:Faculty {name: "Khoa Quản trị Kinh doanh", description: "Đào tạo quản trị kinh doanh"})
MERGE (f12:Faculty {name: "Khoa Tài chính - Kế toán", description: "Đào tạo tài chính và kế toán"})
MERGE (f13:Faculty {name: "Khoa Văn hóa và Du lịch", description: "Đào tạo văn hóa và du lịch"})
MERGE (f14:Faculty {name: "Khoa Khoa học Chính trị", description: "Đào tạo khoa học chính trị"})
MERGE (f15:Faculty {name: "Khoa Toán - Ứng dụng", description: "Đào tạo toán học và ứng dụng"})
MERGE (f16:Faculty {name: "Khoa Điện tử - Viễn thông", description: "Đào tạo điện tử và viễn thông"})
MERGE (f17:Faculty {name: "Khoa Giáo dục Quốc phòng & An ninh - Giáo dục Thể chất", description: "Đào tạo giáo dục quốc phòng và thể chất"})

// Đơn vị trực thuộc
MERGE (i1:Department {name: "Viện Khoa học Dữ liệu và Trí tuệ nhân tạo", description: "Nghiên cứu và đào tạo về AI và khoa học dữ liệu"})
MERGE (i2:Department {name: "Viện Nghiên cứu Môi trường - Sức khỏe", description: "Nghiên cứu về môi trường và sức khỏe"})
MERGE (i3:Department {name: "Trung tâm Thực hành Sư phạm", description: "Tổ chức thực hành sư phạm"})
MERGE (i4:Department {name: "Trường Trung học Thực hành Sài Gòn", description: "Trường thực hành bậc trung học"})
MERGE (i5:Department {name: "Trường Tiểu học Thực hành Sài Gòn", description: "Trường thực hành bậc tiểu học"})

// Tạo quan hệ với trường
WITH u, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, c1, c2, c3, c4, c5, c6, c7, c8, c9, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, i1, i2, i3, i4, i5
MERGE (u)-[:hasDepartment]->(d1)
MERGE (u)-[:hasDepartment]->(d2)
MERGE (u)-[:hasDepartment]->(d3)
MERGE (u)-[:hasDepartment]->(d4)
MERGE (u)-[:hasDepartment]->(d5)
MERGE (u)-[:hasDepartment]->(d6)
MERGE (u)-[:hasDepartment]->(d7)
MERGE (u)-[:hasDepartment]->(d8)
MERGE (u)-[:hasDepartment]->(d9)
MERGE (u)-[:hasDepartment]->(d10)
MERGE (u)-[:hasDepartment]->(d11)
MERGE (u)-[:hasDepartment]->(d12)
MERGE (u)-[:hasDepartment]->(d13)
MERGE (u)-[:hasDepartment]->(d14)
MERGE (u)-[:hasDepartment]->(d15)
MERGE (u)-[:hasDepartment]->(d16)
MERGE (u)-[:hasDepartment]->(d17)
MERGE (u)-[:hasDepartment]->(d18)
MERGE (u)-[:hasDepartment]->(d19)
MERGE (u)-[:hasDepartment]->(d20)
MERGE (u)-[:hasDepartment]->(c1)
MERGE (u)-[:hasDepartment]->(c2)
MERGE (u)-[:hasDepartment]->(c3)
MERGE (u)-[:hasDepartment]->(c4)
MERGE (u)-[:hasDepartment]->(c5)
MERGE (u)-[:hasDepartment]->(c6)
MERGE (u)-[:hasDepartment]->(c7)
MERGE (u)-[:hasDepartment]->(c8)
MERGE (u)-[:hasDepartment]->(c9)
MERGE (u)-[:hasFaculty]->(f1)
MERGE (u)-[:hasFaculty]->(f2)
MERGE (u)-[:hasFaculty]->(f3)
MERGE (u)-[:hasFaculty]->(f4)
MERGE (u)-[:hasFaculty]->(f5)
MERGE (u)-[:hasFaculty]->(f6)
MERGE (u)-[:hasFaculty]->(f7)
MERGE (u)-[:hasFaculty]->(f8)
MERGE (u)-[:hasFaculty]->(f9)
MERGE (u)-[:hasFaculty]->(f10)
MERGE (u)-[:hasFaculty]->(f11)
MERGE (u)-[:hasFaculty]->(f12)
MERGE (u)-[:hasFaculty]->(f13)
MERGE (u)-[:hasFaculty]->(f14)
MERGE (u)-[:hasFaculty]->(f15)
MERGE (u)-[:hasFaculty]->(f16)
MERGE (u)-[:hasFaculty]->(f17)
MERGE (u)-[:hasDepartment]->(i1)
MERGE (u)-[:hasDepartment]->(i2)
MERGE (u)-[:hasDepartment]->(i3)
MERGE (u)-[:hasDepartment]->(i4)
MERGE (u)-[:hasDepartment]->(i5)