MERGE (u:University {name: "Trường Đại học Sài Gòn", description: "Trường Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, đào tạo đa ngành từ trình độ đại học đến sau đại học với các phương thức chính quy và giáo dục thường xuyên"})

MERGE (d1:Degree {name: "Cử nhân", description: "Trình độ đại học với 39 chương trình đào tạo thuộc các lĩnh vực Kinh tế - Kỹ thuật - Công nghệ, Văn hóa xã hội, chính trị, Nghệ thuật và Sư phạm"})
MERGE (d2:Degree {name: "Thạc sĩ", description: "Trình độ sau đại học với 12 chuyên ngành cao học"})
MERGE (d3:Degree {name: "Tiến sĩ", description: "Trình độ sau đại học cao nhất với 05 chuyên ngành tiến sĩ"})
MERGE (d4:Degree {name: "Văn bằng hai", description: "Chương trình đào tạo thứ hai cho người đã có ít nhất một bằng đại học"})
MERGE (d5:Degree {name: "Liên thông", description: "Chương trình đào tạo liên thông từ trình độ thấp lên trình độ cao hơn"})

MERGE (p1:Program {name: "Chính quy", description: "Phương thức đào tạo tập trung toàn thời gian"})
MERGE (p2:Program {name: "Giáo dục thường xuyên", description: "Phương thức đào tạo không tập trung bao gồm vừa làm vừa học, văn bằng hai, liên thông"})

MERGE (c1:Certificate {name: "Bồi dưỡng nghiệp vụ sư phạm", description: "Chứng chỉ bồi dưỡng nghiệp vụ sư phạm cho giảng viên đại học, cao đẳng và giáo viên Tiếng Anh Tiểu học"})
MERGE (c2:Certificate {name: "Công nghệ Thông tin", description: "Chứng chỉ về lĩnh vực Công nghệ Thông tin"})
MERGE (c3:Certificate {name: "Tiếng Anh theo khung năng lực 6 bậc", description: "Chứng chỉ Tiếng Anh theo khung năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam"})

MERGE (a1:Accreditation {name: "Kiểm định chất lượng giáo dục", description: "Được chứng nhận kiểm định chất lượng giáo dục trường đại học vào ngày 13/5/2017"})
MERGE (a2:Award {name: "Huân chương Lao động Hạng Ba", description: "Được Chủ tịch nước trao tặng năm 2018"})

MERGE (f1:Field {name: "Kinh tế - Kỹ thuật - Công nghệ", description: "Lĩnh vực đào tạo về kinh tế, kỹ thuật và công nghệ"})
MERGE (f2:Field {name: "Văn hóa xã hội", description: "Lĩnh vực đào tạo về văn hóa và xã hội"})
MERGE (f3:Field {name: "Chính trị", description: "Lĩnh vực đào tạo về chính trị"})
MERGE (f4:Field {name: "Nghệ thuật", description: "Lĩnh vực đào tạo về nghệ thuật"})
MERGE (f5:Field {name: "Sư phạm", description: "Lĩnh vực đào tạo về sư phạm"})

WITH u, d1, d2, d3, d4, d5, p1, p2, c1, c2, c3, a1, a2, f1, f2, f3, f4, f5
MERGE (u)-[:hasDegree]->(d1)
MERGE (u)-[:hasDegree]->(d2)
MERGE (u)-[:hasDegree]->(d3)
MERGE (u)-[:hasDegree]->(d4)
MERGE (u)-[:hasDegree]->(d5)
MERGE (u)-[:offersProgram]->(p1)
MERGE (u)-[:offersProgram]->(p2)
MERGE (u)-[:offersCertificate]->(c1)
MERGE (u)-[:offersCertificate]->(c2)
MERGE (u)-[:offersCertificate]->(c3)
MERGE (u)-[:hasAccreditation]->(a1)
MERGE (u)-[:hasAward]->(a2)
MERGE (u)-[:hasField]->(f1)
MERGE (u)-[:hasField]->(f2)
MERGE (u)-[:hasField]->(f3)
MERGE (u)-[:hasField]->(f4)
MERGE (u)-[:hasField]->(f5)