MERGE (u:University {name: "Trường Đại học Sài Gòn", description: "Trường Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, đào tạo đa ngành từ trình độ đại học đến sau đại học với các phương thức chính quy và giáo dục thường xuyên"})

// Các chương trình đào tạo hệ chính quy - đại trà
MERGE (p1:Program {name: "Giáo dục Chính trị - Du lịch", description: "Chương trình đào tạo kết hợp kiến thức chính trị và du lịch"})
MERGE (p2:Program {name: "Giáo dục Mầm non - Kế toán", description: "Chương trình đào tạo kết hợp giáo dục mầm non và kế toán"})
MERGE (p3:Program {name: "Giáo dục Tiểu học - Khoa học Môi trường", description: "Chương trình đào tạo kết hợp giáo dục tiểu học và khoa học môi trường"})
MERGE (p4:Program {name: "Sư phạm Âm nhạc - Kinh doanh Quốc tế", description: "Chương trình đào tạo kết hợp sư phạm âm nhạc và kinh doanh quốc tế"})
MERGE (p5:Program {name: "Sư phạm Địa lý - Kỹ thuật Điện", description: "Chương trình đào tạo kết hợp sư phạm địa lý và kỹ thuật điện"})
MERGE (p6:Program {name: "Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông", description: "Chương trình đào tạo kết hợp sư phạm hóa học và kỹ thuật điện tử viễn thông"})
MERGE (p7:Program {name: "Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm", description: "Chương trình đào tạo kết hợp sư phạm khoa học tự nhiên và kỹ thuật phần mềm"})
MERGE (p8:Program {name: "Sư phạm Lịch sử - Luật", description: "Chương trình đào tạo kết hợp sư phạm lịch sử và luật"})
MERGE (p9:Program {name: "Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh", description: "Chương trình đào tạo kết hợp sư phạm lịch sử, địa lý và ngôn ngữ Anh"})
MERGE (p10:Program {name: "Sư phạm Mỹ thuật - Quản lý Giáo dục", description: "Chương trình đào tạo kết hợp sư phạm mỹ thuật và quản lý giáo dục"})
MERGE (p11:Program {name: "Sư phạm Ngữ Văn - Quản trị Kinh doanh", description: "Chương trình đào tạo kết hợp sư phạm ngữ văn và quản trị kinh doanh"})
MERGE (p12:Program {name: "Sư phạm Sinh học - Quản trị Văn phòng", description: "Chương trình đào tạo kết hợp sư phạm sinh học và quản trị văn phòng"})
MERGE (p13:Program {name: "Sư phạm Tiếng Anh - Quốc tế học", description: "Chương trình đào tạo kết hợp sư phạm tiếng Anh và quốc tế học"})
MERGE (p14:Program {name: "Sư phạm Toán học - Tài chính - Ngân hàng", description: "Chương trình đào tạo kết hợp sư phạm toán học và tài chính ngân hàng"})
MERGE (p15:Program {name: "Sư phạm Vật lý - Tâm lý học", description: "Chương trình đào tạo kết hợp sư phạm vật lý và tâm lý học"})
MERGE (p16:Program {name: "CNKT Điện tử - Viễn thông - Thanh nhạc", description: "Chương trình đào tạo kết hợp công nghệ kỹ thuật điện tử viễn thông và thanh nhạc"})
MERGE (p17:Program {name: "CNKT Điện, Điện tử - Thông tin - Thư viện", description: "Chương trình đào tạo kết hợp công nghệ kỹ thuật điện, điện tử và thông tin thư viện"})
MERGE (p18:Program {name: "Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng", description: "Chương trình đào tạo kết hợp công nghệ kỹ thuật môi trường và toán ứng dụng"})
MERGE (p19:Program {name: "Công nghệ Thông tin - Việt Nam học", description: "Chương trình đào tạo kết hợp công nghệ thông tin và Việt Nam học"})

// Chương trình chất lượng cao
MERGE (p20:Program {name: "Công nghệ Thông tin (Chất lượng cao)", description: "Chương trình đào tạo công nghệ thông tin chất lượng cao"})

// Chương trình sau đại học
MERGE (p21:Program {name: "Hóa hữu cơ (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ hóa hữu cơ"})
MERGE (p22:Program {name: "Hóa lý thuyết và Hóa lý (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ hóa lý thuyết và hóa lý"})
MERGE (p23:Program {name: "Khoa học Máy tính (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ khoa học máy tính"})
MERGE (p24:Program {name: "Lịch sử Việt Nam (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ lịch sử Việt Nam"})
MERGE (p25:Program {name: "Văn học Việt Nam (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ văn học Việt Nam"})
MERGE (p26:Program {name: "LL & PPDH bộ môn Toán (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ lý luận và phương pháp dạy học bộ môn toán"})
MERGE (p27:Program {name: "Luật dân sự và tố tụng dân sự (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ luật dân sự và tố tụng dân sự"})
MERGE (p28:Program {name: "Ngôn ngữ học (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ ngôn ngữ học"})
MERGE (p29:Program {name: "Quản lý Giáo dục (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ quản lý giáo dục"})
MERGE (p30:Program {name: "Quản trị Kinh doanh (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ quản trị kinh doanh"})
MERGE (p31:Program {name: "Tài chính – Ngân hàng (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ tài chính ngân hàng"})
MERGE (p32:Program {name: "Toán Giải tích (Thạc sĩ)", description: "Chương trình đào tạo thạc sĩ toán giải tích"})

// Chương trình tiến sĩ
MERGE (p33:Program {name: "Hóa hữu cơ (Tiến sĩ)", description: "Chương trình đào tạo tiến sĩ hóa hữu cơ"})
MERGE (p34:Program {name: "Lịch sử Việt Nam (Tiến sĩ)", description: "Chương trình đào tạo tiến sĩ lịch sử Việt Nam"})
MERGE (p35:Program {name: "Quản lý Giáo dục (Tiến sĩ)", description: "Chương trình đào tạo tiến sĩ quản lý giáo dục"})
MERGE (p36:Program {name: "Toán Giải tích (Tiến sĩ)", description: "Chương trình đào tạo tiến sĩ toán giải tích"})
MERGE (p37:Program {name: "Quản trị Kinh doanh (Tiến sĩ)", description: "Chương trình đào tạo tiến sĩ quản trị kinh doanh"})

// Chương trình giáo dục thường xuyên
MERGE (p38:Program {name: "Liên thông Công nghệ Thông tin", description: "Chương trình liên thông đại học ngành công nghệ thông tin"})
MERGE (p39:Program {name: "Liên thông Kế toán", description: "Chương trình liên thông đại học ngành kế toán"})
MERGE (p40:Program {name: "Liên thông Quản trị Kinh doanh", description: "Chương trình liên thông đại học ngành quản trị kinh doanh"})
MERGE (p41:Program {name: "Liên thông Giáo dục Mầm non", description: "Chương trình liên thông đại học ngành giáo dục mầm non"})
MERGE (p42:Program {name: "Liên thông Giáo dục Tiểu học", description: "Chương trình liên thông đại học ngành giáo dục tiểu học"})
MERGE (p43:Program {name: "Văn bằng hai Ngôn ngữ Anh", description: "Chương trình văn bằng hai ngành ngôn ngữ Anh"})
MERGE (p44:Program {name: "Văn bằng hai Kế toán", description: "Chương trình văn bằng hai ngành kế toán"})
MERGE (p45:Program {name: "Văn bằng hai Luật", description: "Chương trình văn bằng hai ngành luật"})
MERGE (p46:Program {name: "Văn bằng hai Quản trị Kinh doanh", description: "Chương trình văn bằng hai ngành quản trị kinh doanh"})
MERGE (p47:Program {name: "Văn bằng hai Giáo dục Tiểu học", description: "Chương trình văn bằng hai ngành giáo dục tiểu học"})
MERGE (p48:Program {name: "Văn bằng hai Quản lý Giáo dục", description: "Chương trình văn bằng hai ngành quản lý giáo dục"})
MERGE (p49:Program {name: "Vừa làm vừa học Quản trị Kinh doanh", description: "Chương trình vừa làm vừa học ngành quản trị kinh doanh"})
MERGE (p50:Program {name: "Vừa làm vừa học Tài chính - Ngân hàng", description: "Chương trình vừa làm vừa học ngành tài chính ngân hàng"})
MERGE (p51:Program {name: "Vừa làm vừa học Tài chính - Kế toán", description: "Chương trình vừa làm vừa học ngành tài chính kế toán"})
MERGE (p52:Program {name: "Vừa làm vừa học Luật", description: "Chương trình vừa làm vừa học ngành luật"})
MERGE (p53:Program {name: "Vừa làm vừa học Giáo dục Tiểu học", description: "Chương trình vừa làm vừa học ngành giáo dục tiểu học"})
MERGE (p54:Program {name: "Vừa làm vừa học Giáo dục Mầm non", description: "Chương trình vừa làm vừa học ngành giáo dục mầm non"})

// Cơ sở vật chất
MERGE (c1:Campus {name: "Cơ sở 273 An Dương Vương", description: "Cơ sở chính tại Q.5 với diện tích 42.743 m2"})
MERGE (c2:Campus {name: "Cơ sở 105 Bà Huyện Thanh Quan", description: "Cơ sở tại Q.3 với diện tích 4.823 m2"})
MERGE (c3:Campus {name: "Cơ sở 04 Tôn Đức Thắng", description: "Cơ sở tại Q.1 với diện tích 19.655 m2"})
MERGE (c4:Campus {name: "Ký túc xá 99 An Dương Vương", description: "Ký túc xá sinh viên tại Q.8 với diện tích 4.800 m2"})

// Tạo quan hệ với trường
WITH u, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p30, p31, p32, p33, p34, p35, p36, p37, p38, p39, p40, p41, p42, p43, p44, p45, p46, p47, p48, p49, p50, p51, p52, p53, p54, c1, c2, c3, c4
MERGE (u)-[:offersProgram]->(p1)
MERGE (u)-[:offersProgram]->(p2)
MERGE (u)-[:offersProgram]->(p3)
MERGE (u)-[:offersProgram]->(p4)
MERGE (u)-[:offersProgram]->(p5)
MERGE (u)-[:offersProgram]->(p6)
MERGE (u)-[:offersProgram]->(p7)
MERGE (u)-[:offersProgram]->(p8)
MERGE (u)-[:offersProgram]->(p9)
MERGE (u)-[:offersProgram]->(p10)
MERGE (u)-[:offersProgram]->(p11)
MERGE (u)-[:offersProgram]->(p12)
MERGE (u)-[:offersProgram]->(p13)
MERGE (u)-[:offersProgram]->(p14)
MERGE (u)-[:offersProgram]->(p15)
MERGE (u)-[:offersProgram]->(p16)
MERGE (u)-[:offersProgram]->(p17)
MERGE (u)-[:offersProgram]->(p18)
MERGE (u)-[:offersProgram]->(p19)
MERGE (u)-[:offersProgram]->(p20)
MERGE (u)-[:offersProgram]->(p21)
MERGE (u)-[:offersProgram]->(p22)
MERGE (u)-[:offersProgram]->(p23)
MERGE (u)-[:offersProgram]->(p24)
MERGE (u)-[:offersProgram]->(p25)
MERGE (u)-[:offersProgram]->(p26)
MERGE (u)-[:offersProgram]->(p27)
MERGE (u)-[:offersProgram]->(p28)
MERGE (u)-[:offersProgram]->(p29)
MERGE (u)-[:offersProgram]->(p30)
MERGE (u)-[:offersProgram]->(p31)
MERGE (u)-[:offersProgram]->(p32)
MERGE (u)-[:offersProgram]->(p33)
MERGE (u)-[:offersProgram]->(p34)
MERGE (u)-[:offersProgram]->(p35)
MERGE (u)-[:offersProgram]->(p36)
MERGE (u)-[:offersProgram]->(p37)
MERGE (u)-[:offersProgram]->(p38)
MERGE (u)-[:offersProgram]->(p39)
MERGE (u)-[:offersProgram]->(p40)
MERGE (u)-[:offersProgram]->(p41)
MERGE (u)-[:offersProgram]->(p42)
MERGE (u)-[:offersProgram]->(p43)
MERGE (u)-[:offersProgram]->(p44)
MERGE (u)-[:offersProgram]->(p45)
MERGE (u)-[:offersProgram]->(p46)
MERGE (u)-[:offersProgram]->(p47)
MERGE (u)-[:offersProgram]->(p48)
MERGE (u)-[:offersProgram]->(p49)
MERGE (u)-[:offersProgram]->(p50)
MERGE (u)-[:offersProgram]->(p51)
MERGE (u)-[:offersProgram]->(p52)
MERGE (u)-[:offersProgram]->(p53)
MERGE (u)-[:offersProgram]->(p54)
MERGE (u)-[:hasCampus]->(c1)
MERGE (u)-[:hasCampus]->(c2)
MERGE (u)-[:hasCampus]->(c3)
MERGE (u)-[:hasCampus]->(c4)