MERGE (university:University {name: 'Trường Đại học Sài Gòn', description: 'Cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, chịu sự quản lý nhà nước về giáo dục của Bộ Giáo dục và Đào tạo; là trường đại học đào tạo đa ngành, đa lĩnh vực.'})
MERGE (department1:Department {name: 'Đảng ủy', description: 'Bộ phận quản lý và lãnh đạo của trường.'})
MERGE (department2:Department {name: 'Hội đồng trường', description: 'Cơ quan quyết định các vấn đề quan trọng của trường.'})
MERGE (department3:Department {name: 'Hiệu trưởng', description: 'Người đứng đầu trường đại học.'})
MERGE (department4:Department {name: 'Phó hiệu trưởng', description: 'Người hỗ trợ hiệu trưởng trong công tác quản lý.'})
MERGE (department5:Department {name: 'Công đoàn', description: 'Tổ chức đại diện cho quyền lợi của cán bộ, giảng viên.'})
MERGE (department6:Department {name: 'Đoàn thanh niên', description: 'Tổ chức thanh niên trong trường.'})
MERGE (department7:Department {name: 'Hội sinh viên', description: 'Tổ chức đại diện cho sinh viên.'})
MERGE (department8:Department {name: 'Đào tạo', description: 'Bộ phận phụ trách công tác đào tạo.'})
MERGE (department9:Department {name: 'Tổ chức - Cán bộ', description: 'Bộ phận quản lý nhân sự.'})
MERGE (department10:Department {name: 'Văn phòng', description: 'Bộ phận hành chính của trường.'})
MERGE (department11:Department {name: 'Kế hoạch - Tài chính', description: 'Bộ phận quản lý tài chính và kế hoạch.'})
MERGE (department12:Department {name: 'Công tác sinh viên', description: 'Bộ phận hỗ trợ sinh viên.'})
MERGE (department13:Department {name: 'Quản lý khoa học', description: 'Bộ phận phụ trách nghiên cứu khoa học.'})
MERGE (department14:Department {name: 'Đào tạo sau đại học', description: 'Bộ phận phụ trách đào tạo sau đại học.'})
MERGE (department15:Department {name: 'Thanh tra - Pháp chế', description: 'Bộ phận kiểm tra và đảm bảo pháp lý.'})
MERGE (department16:Department {name: 'Khảo thí & Bảo đảm chất lượng', description: 'Bộ phận đảm bảo chất lượng đào tạo.'})
MERGE (department17:Department {name: 'Ban quản lý dự án và hạ tầng', description: 'Bộ phận quản lý các dự án và cơ sở hạ tầng.'})
MERGE (department18:Department {name: 'Hợp tác quốc tế & Doanh nghiệp', description: 'Bộ phận phụ trách hợp tác quốc tế.'})
MERGE (department19:Department {name: 'Thiết bị', description: 'Bộ phận quản lý thiết bị học tập.'})
MERGE (department20:Department {name: 'Giáo dục thường xuyên', description: 'Bộ phận phụ trách giáo dục thường xuyên.'})
MERGE (trainingProgram1:TrainingProgram {name: 'Chương trình đào tạo tiến sĩ', description: 'Chương trình đào tạo trình độ tiến sĩ.'})
MERGE (trainingProgram2:TrainingProgram {name: 'Chương trình đào tạo cao học', description: 'Chương trình đào tạo trình độ cao học.'})
MERGE (trainingProgram3:TrainingProgram {name: 'Chương trình đào tạo đại học', description: 'Chương trình đào tạo trình độ đại học.'})
MERGE (university)-[:hasDepartment]->(department1)
MERGE (university)-[:hasDepartment]->(department2)
MERGE (university)-[:hasDepartment]->(department3)
MERGE (university)-[:hasDepartment]->(department4)
MERGE (university)-[:hasDepartment]->(department5)
MERGE (university)-[:hasDepartment]->(department6)
MERGE (university)-[:hasDepartment]->(department7)
MERGE (university)-[:hasDepartment]->(department8)
MERGE (university)-[:hasDepartment]->(department9)
MERGE (university)-[:hasDepartment]->(department10)
MERGE (university)-[:hasDepartment]->(department11)
MERGE (university)-[:hasDepartment]->(department12)
MERGE (university)-[:hasDepartment]->(department13)
MERGE (university)-[:hasDepartment]->(department14)
MERGE (university)-[:hasDepartment]->(department15)
MERGE (university)-[:hasDepartment]->(department16)
MERGE (university)-[:hasDepartment]->(department17)
MERGE (university)-[:hasDepartment]->(department18)
MERGE (university)-[:hasDepartment]->(department19)
MERGE (university)-[:hasDepartment]->(department20)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram1)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram2)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram3)
MERGE (trainingProgram4:TrainingProgram {name: 'Chương trình đại trà', description: 'Chương trình đào tạo đại trà cho sinh viên.'})
MERGE (trainingProgram5:TrainingProgram {name: 'Giáo dục Chính trị', description: 'Chương trình đào tạo về giáo dục chính trị.'})
MERGE (trainingProgram6:TrainingProgram {name: 'Giáo dục Mầm non', description: 'Chương trình đào tạo giáo dục mầm non.'})
MERGE (trainingProgram7:TrainingProgram {name: 'Giáo dục Tiểu học', description: 'Chương trình đào tạo giáo dục tiểu học.'})
MERGE (trainingProgram8:TrainingProgram {name: 'Sư phạm Âm nhạc', description: 'Chương trình đào tạo sư phạm âm nhạc.'})
MERGE (trainingProgram9:TrainingProgram {name: 'Sư phạm Địa lý', description: 'Chương trình đào tạo sư phạm địa lý.'})
MERGE (trainingProgram10:TrainingProgram {name: 'Sư phạm Hóa học', description: 'Chương trình đào tạo sư phạm hóa học.'})
MERGE (trainingProgram11:TrainingProgram {name: 'Sư phạm Khoa học Tự nhiên', description: 'Chương trình đào tạo sư phạm khoa học tự nhiên.'})
MERGE (trainingProgram12:TrainingProgram {name: 'Sư phạm Lịch sử', description: 'Chương trình đào tạo sư phạm lịch sử.'})
MERGE (trainingProgram13:TrainingProgram {name: 'Sư phạm Lịch sử - Địa lý', description: 'Chương trình đào tạo sư phạm lịch sử - địa lý.'})
MERGE (trainingProgram14:TrainingProgram {name: 'Sư phạm Mỹ thuật', description: 'Chương trình đào tạo sư phạm mỹ thuật.'})
MERGE (trainingProgram15:TrainingProgram {name: 'Sư phạm Ngữ Văn', description: 'Chương trình đào tạo sư phạm ngữ văn.'})
MERGE (trainingProgram16:TrainingProgram {name: 'Sư phạm Sinh học', description: 'Chương trình đào tạo sư phạm sinh học.'})
MERGE (trainingProgram17:TrainingProgram {name: 'Sư phạm Tiếng Anh', description: 'Chương trình đào tạo sư phạm tiếng Anh.'})
MERGE (trainingProgram18:TrainingProgram {name: 'Sư phạm Toán học', description: 'Chương trình đào tạo sư phạm toán học.'})
MERGE (trainingProgram19:TrainingProgram {name: 'Sư phạm Vật lý', description: 'Chương trình đào tạo sư phạm vật lý.'})
MERGE (trainingProgram20:TrainingProgram {name: 'CNKT Điện tử - Viễn thông', description: 'Chương trình đào tạo công nghệ kỹ thuật điện tử - viễn thông.'})
MERGE (trainingProgram21:TrainingProgram {name: 'CNKT Điện, Điện tử', description: 'Chương trình đào tạo công nghệ kỹ thuật điện và điện tử.'})
MERGE (trainingProgram22:TrainingProgram {name: 'Công nghệ Kỹ thuật Môi trường', description: 'Chương trình đào tạo công nghệ kỹ thuật môi trường.'})
MERGE (trainingProgram23:TrainingProgram {name: 'Công nghệ Thông tin', description: 'Chương trình đào tạo công nghệ thông tin.'})
MERGE (trainingProgram24:TrainingProgram {name: 'Du lịch', description: 'Chương trình đào tạo ngành du lịch.'})
MERGE (trainingProgram25:TrainingProgram {name: 'Kế toán', description: 'Chương trình đào tạo ngành kế toán.'})
MERGE (trainingProgram26:TrainingProgram {name: 'Khoa học Môi trường', description: 'Chương trình đào tạo khoa học môi trường.'})
MERGE (trainingProgram27:TrainingProgram {name: 'Kinh doanh Quốc tế', description: 'Chương trình đào tạo kinh doanh quốc tế.'})
MERGE (trainingProgram28:TrainingProgram {name: 'Kỹ thuật Điện', description: 'Chương trình đào tạo kỹ thuật điện.'})
MERGE (trainingProgram29:TrainingProgram {name: 'Kỹ thuật Điện tử - Viễn thông', description: 'Chương trình đào tạo kỹ thuật điện tử - viễn thông.'})
MERGE (trainingProgram30:TrainingProgram {name: 'Kỹ thuật Phần mềm', description: 'Chương trình đào tạo kỹ thuật phần mềm.'})
MERGE (trainingProgram31:TrainingProgram {name: 'Luật', description: 'Chương trình đào tạo ngành luật.'})
MERGE (trainingProgram32:TrainingProgram {name: 'Ngôn ngữ Anh', description: 'Chương trình đào tạo ngôn ngữ Anh.'})
MERGE (trainingProgram33:TrainingProgram {name: 'Quản lý Giáo dục', description: 'Chương trình đào tạo quản lý giáo dục.'})
MERGE (trainingProgram34:TrainingProgram {name: 'Quản trị Kinh doanh', description: 'Chương trình đào tạo quản trị kinh doanh.'})
MERGE (trainingProgram35:TrainingProgram {name: 'Quản trị Văn phòng', description: 'Chương trình đào tạo quản trị văn phòng.'})
MERGE (trainingProgram36:TrainingProgram {name: 'Quốc tế học', description: 'Chương trình đào tạo quốc tế học.'})
MERGE (trainingProgram37:TrainingProgram {name: 'Tài chính - Ngân hàng', description: 'Chương trình đào tạo tài chính - ngân hàng.'})
MERGE (trainingProgram38:TrainingProgram {name: 'Tâm lý học', description: 'Chương trình đào tạo tâm lý học.'})
MERGE (trainingProgram39:TrainingProgram {name: 'Thanh nhạc', description: 'Chương trình đào tạo thanh nhạc.'})
MERGE (trainingProgram40:TrainingProgram {name: 'Thông tin - Thư viện', description: 'Chương trình đào tạo thông tin - thư viện.'})
MERGE (trainingProgram41:TrainingProgram {name: 'Toán Ứng dụng', description: 'Chương trình đào tạo toán ứng dụng.'})
MERGE (trainingProgram42:TrainingProgram {name: 'Việt Nam học', description: 'Chương trình đào tạo về Việt Nam học.'})
MERGE (trainingProgram43:TrainingProgram {name: 'Hóa hữu cơ', description: 'Chương trình đào tạo hóa hữu cơ.'})
MERGE (trainingProgram44:TrainingProgram {name: 'Hóa lý thuyết và Hóa lý', description: 'Chương trình đào tạo hóa lý thuyết và hóa lý.'})
MERGE (trainingProgram45:TrainingProgram {name: 'Khoa học Máy tính', description: 'Chương trình đào tạo khoa học máy tính.'})
MERGE (trainingProgram46:TrainingProgram {name: 'Lịch sử Việt Nam', description: 'Chương trình đào tạo lịch sử Việt Nam.'})
MERGE (trainingProgram47:TrainingProgram {name: 'LL & PPDH bộ môn Toán', description: 'Chương trình đào tạo LL & PPDH bộ môn Toán.'})
MERGE (trainingProgram48:TrainingProgram {name: 'Ngôn ngữ học', description: 'Chương trình đào tạo ngôn ngữ học.'})
MERGE (trainingProgram49:TrainingProgram {name: 'Quản lý Giáo dục', description: 'Chương trình đào tạo quản lý giáo dục.'})
MERGE (trainingProgram50:TrainingProgram {name: 'Toán Giải tích', description: 'Chương trình đào tạo toán giải tích.'})
MERGE (trainingProgram51:TrainingProgram {name: 'Quản trị Kinh doanh', description: 'Chương trình đào tạo quản trị kinh doanh.'})
MERGE (trainingProgram52:TrainingProgram {name: 'Tài chính - Ngân hàng', description: 'Chương trình đào tạo tài chính - ngân hàng.'})
MERGE (trainingProgram53:TrainingProgram {name: 'Toán Giải tích', description: 'Chương trình đào tạo toán giải tích.'})
MERGE (trainingProgram54:TrainingProgram {name: 'Văn học Việt Nam', description: 'Chương trình đào tạo văn học Việt Nam.'})
MERGE (trainingProgram55:TrainingProgram {name: 'Luật dân sự và tố tụng dân sự', description: 'Chương trình đào tạo luật dân sự và tố tụng dân sự.'})
MERGE (university)-[:hasTrainingProgram]->(trainingProgram4)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram5)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram6)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram7)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram8)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram9)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram10)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram11)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram12)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram13)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram14)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram15)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram16)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram17)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram18)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram19)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram20)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram21)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram22)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram23)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram24)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram25)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram26)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram27)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram28)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram29)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram30)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram31)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram32)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram33)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram34)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram35)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram36)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram37)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram38)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram39)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram40)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram41)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram42)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram43)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram44)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram45)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram46)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram47)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram48)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram49)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram50)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram51)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram52)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram53)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram54)
MERGE (university)-[:hasTrainingProgram]->(trainingProgram55)
MERGE (internationalCooperation1:InternationalCooperation {name: 'Chương trình Cử nhân Quốc tế Quản trị Kinh doanh và Quản lý Thương mại Điện tử', description: 'Chương trình liên kết đào tạo giữa trường Đại học Sài Gòn và trường Đại học Khoa học Ứng dụng IMC Krems (Cộng hòa Áo).' })
MERGE (internationalCooperation2:InternationalCooperation {name: 'Chương trình đào tạo tiếng Hoa', description: 'Chương trình liên kết với Hiệp hội Phát triển Kinh tế Văn hóa Giáo dục Đài Việt.' })
MERGE (internationalCooperation3:InternationalCooperation {name: 'Học bổng toàn phần của Bộ Y tế Singapore', description: 'Chương trình học bổng toàn phần cho sinh viên đào tạo Trợ lý bác sĩ.' })
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation1)
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation2)
MERGE (university)-[:hasScholarship]->(internationalCooperation3)
MERGE (internationalCooperation4:InternationalCooperation {name: 'Chương trình học bổng Cử nhân hệ chính quy', description: 'Chương trình học bổng cho sinh viên các khối ngành Kinh tế, Thương mại, Thực phẩm, Dịch vụ, Công nghệ Thông tin, Kỹ thuật.'})
MERGE (internationalCooperation5:InternationalCooperation {name: 'Chương trình chuyển tiếp các ngành', description: 'Ký kết hợp tác và xây dựng chương trình chuyển tiếp các ngành Công nghệ thông tin, Ngôn ngữ Anh, Sư phạm Anh, Quản trị kinh doanh, Tài chính - Ngân hàng thuộc Đại học Huddersfield.'})
MERGE (internationalCooperation6:InternationalCooperation {name: 'Thạc sĩ Giảng dạy tiếng Anh', description: 'Chương trình Thạc sĩ Giảng dạy tiếng Anh (Master of TESOL) thuộc Đại học Huddersfield (Vương quốc Anh).'})

MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation4)
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation5)
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation6)
MERGE (journal:Journal {name: 'Tạp chí Khoa học Đại học Sài Gòn', description: 'Cơ quan chủ quản: Trường Đại học Sài Gòn. Đối tượng phục vụ: Cán bộ giảng dạy, nghiên cứu, quản lý, sinh viên các trường đại học, cao đẳng, các viện, học viện, các trung tâm nghiên cứu.'})
MERGE (journal)-[:hasPublicationType]->(university)
MERGE (journal)-[:hasCitationStandard]->(journal)
MERGE (journal)-[:hasPublicationRule]->(journal)
MERGE (journal)-[:hasPublicationRule]->(journal)
MERGE (journal)-[:hasTechnicalRequirement]->(journal)
MERGE (journal)-[:hasPublicationType]->(journal)