MERGE (university:University {name: 'Trường Đại học Sài Gòn'})
MERGE (department1:Department {name: 'Giáo dục Chính trị - Du lịch'})
MERGE (department2:Department {name: 'Giáo dục Mầm non - Kế toán'})
MERGE (department3:Department {name: 'Giáo dục Tiểu học - Khoa học Môi trường'})
MERGE (department4:Department {name: 'Sư phạm Âm nhạc - Kinh doanh Quốc tế'})
MERGE (department5:Department {name: 'Sư phạm Địa lý - Kỹ thuật Điện'})
MERGE (department6:Department {name: 'Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông'})
MERGE (department7:Department {name: 'Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm'})
MERGE (department8:Department {name: 'Sư phạm Lịch sử - Luật'})
MERGE (department9:Department {name: 'Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh'})
MERGE (department10:Department {name: 'Sư phạm Mỹ thuật - Quản lý Giáo dục'})
MERGE (department11:Department {name: 'Sư phạm Ngữ Văn - Quản trị Kinh doanh'})
MERGE (department12:Department {name: 'Sư phạm Sinh học - Quản trị Văn phòng'})
MERGE (department13:Department {name: 'Sư phạm Tiếng Anh - Quốc tế học'})
MERGE (department14:Department {name: 'Sư phạm Toán học - Tài chính - Ngân hàng'})
MERGE (department15:Department {name: 'Sư phạm Vật lý - Tâm lý học'})
MERGE (department16:Department {name: 'CNKT Điện tử - Viễn thông - Thanh nhạc'})
MERGE (department17:Department {name: 'CNKT Điện, Điện tử - Thông tin - Thư viện'})
MERGE (department18:Department {name: 'Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng'})
MERGE (department19:Department {name: 'Công nghệ Thông tin - Việt Nam học'})
MERGE (trainingProgram1:TrainingProgram {name: 'Chương trình đại trà'})
MERGE (trainingProgram2:TrainingProgram {name: 'Chương trình chất lượng cao: Công nghệ Thông tin'})
MERGE (trainingProgram3:TrainingProgram {name: 'Trình độ Sau Đại học'})
MERGE (trainingProgram4:TrainingProgram {name: 'Trình độ Tiến sĩ'})
MERGE (university)-[:hasDepartment]->(department1)
MERGE (university)-[:hasDepartment]->(department2)
MERGE (university)-[:hasDepartment]->(department3)
MERGE (university)-[:hasDepartment]->(department4)
MERGE (university)-[:hasDepartment]->(department5)
MERGE (university)-[:hasDepartment]->(department6)
MERGE (university)-[:hasDepartment]->(department7)
MERGE (university)-[:hasDepartment]->(department8)
MERGE (university)-[:hasDepartment]->(department9)
MERGE (university)-[:hasDepartment]->(department10)
MERGE (university)-[:hasDepartment]->(department11)
MERGE (university)-[:hasDepartment]->(department12)
MERGE (university)-[:hasDepartment]->(department13)
MERGE (university)-[:hasDepartment]->(department14)
MERGE (university)-[:hasDepartment]->(department15)
MERGE (university)-[:hasDepartment]->(department16)
MERGE (university)-[:hasDepartment]->(department17)
MERGE (university)-[:hasDepartment]->(department18)
MERGE (university)-[:hasDepartment]->(department19)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram1)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram2)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram3)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram4)
MERGE (trainingProgram5:TrainingProgram {name: 'Giáo dục thường xuyên'})
MERGE (trainingProgram6:TrainingProgram {name: 'Đào tạo Đại học liên thông'})
MERGE (trainingProgram7:TrainingProgram {name: 'Đào tạo văn bằng thứ hai trình độ đại học'})
MERGE (trainingProgram8:TrainingProgram {name: 'Đào tạo hệ đại học vừa làm vừa học'})
MERGE (campus1:Campus {name: 'Cơ sở 273 An Dương Vương, Q.5', area: 42743})
MERGE (campus2:Campus {name: 'Cơ sở 105 Bà Huyện Thanh Quan, Q.3', area: 4823})
MERGE (campus3:Campus {name: 'Cơ sở 04 Tôn Đức Thắng, Q.1', area: 19655})
MERGE (campus4:Campus {name: 'Ký túc xá 99 An Dương Vương, Q.8', area: 4800})
MERGE (internationalCooperation:InternationalCooperation {name: 'Hợp tác quốc tế'})
MERGE (university)-[:offersTrainingProgram]->(trainingProgram5)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram6)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram7)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram8)
MERGE (university)-[:hasCampus]->(campus1)
MERGE (university)-[:hasCampus]->(campus2)
MERGE (university)-[:hasCampus]->(campus3)
MERGE (university)-[:hasCampus]->(campus4)
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation)
MERGE (trainingProgram9:TrainingProgram {name: 'Chương trình liên kết đào tạo Cử nhân Quản trị Kinh doanh và Quản lý Thương mại Điện tử'})
MERGE (trainingProgram10:TrainingProgram {name: 'Chương trình đào tạo tiếng Hoa'})
MERGE (scholarship1:Scholarship {name: 'Học bổng toàn phần của Bộ Y tế Singapore - Asian Nursing Scholarship'})
MERGE (scholarship2:Scholarship {name: 'Học bổng của Bộ Giáo dục Đài Loan'})
MERGE (internationalCooperation2:InternationalCooperation {name: 'Chương trình liên kết đào tạo với Đại học Huddersfield'})
MERGE (university)-[:offersTrainingProgram]->(trainingProgram9)
MERGE (university)-[:offersTrainingProgram]->(trainingProgram10)
MERGE (university)-[:hasScholarship]->(scholarship1)
MERGE (university)-[:hasScholarship]->(scholarship2)
MERGE (university)-[:hasInternationalCooperation]->(internationalCooperation2)
MERGE (researchTopic1:ResearchTopic {name: 'Đề tài Nghiên cứu khoa học cấp cơ sở'})
MERGE (journal:Journal {name: 'Tạp chí Khoa học Đại học Sài Gòn'})
MERGE (university)-[:hasResearchTopic]->(researchTopic1)
MERGE (university)-[:hasJournal]->(journal)
MERGE (journal)-[:hasPublicationType]->(publicationType1:Journal {name: 'Giấy phép hoạt động tạp chí', details: 'Số 22/GP-BTTTT do Bộ Thông tin và Truyền thông cấp ngày 23/01/2015'})
MERGE (journal)-[:hasPublicationType]->(publicationType2:Journal {name: 'Mã số chuẩn quốc tế (ISSN)', details: '1859-3208'})
MERGE (journal)-[:hasPublicationGuidelines]->(guidelines:Journal {name: 'Quy định chung về bài báo khoa học', details: 'Phải nêu rõ mục tiêu nghiên cứu; cần có các kết quả mới...'})
MERGE (journal)-[:hasTechnicalRequirements]->(technicalRequirements:Journal {name: 'Thể lệ gửi bài đăng tạp chí Khoa học Đại Học Sài Gòn', details: 'Bài gửi đăng trên Tạp chí phải là công trình khoa học...'})
MERGE (trainingInfo:TrainingProgram {name: 'Thông tin đào tạo'})
MERGE (university)-[:offersTrainingProgram]->(trainingInfo)
MERGE (trainingInfo)-[:hasFieldOfStudy]->(field1:TrainingProgram {name: 'Quy định về số tiết và thời gian của các tiết học trong ngày'})
MERGE (trainingInfo)-[:hasFieldOfStudy]->(field2:TrainingProgram {name: 'Thông tin về mã phòng học'})
MERGE (trainingInfo)-[:hasFieldOfStudy]->(field3:TrainingProgram {name: 'Trang Phòng Đào tạo'})
MERGE (trainingInfo)-[:hasFieldOfStudy]->(field4:TrainingProgram {name: 'Trang Thông tin Đào tạo'})