MERGE (university:University {name: 'Trường Đại học Sài Gòn', description: 'Trường Đại học Sài Gòn là cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, chịu sự quản lý nhà nước về giáo dục của Bộ Giáo dục và Đào tạo; là trường đại học đào tạo đa ngành, đa lĩnh vực. Trường Đại học Sài Gòn đào tạo từ trình độ đại học và sau đại học, theo 2 phương thức: chính quy và giáo dục thường xuyên (vừa làm vừa học, văn bằng hai, liên thông). Hiện nay, Trường đang tổ chức đào tạo 05 chuyên ngành tiến sĩ, 12 chuyên ngành cao học và 39 chương trình đào tạo trình độ đại học thuộc các lĩnh vực: Kinh tế - Kỹ thuật - Công nghệ, Văn hóa xã hội, chính trị, Nghệ thuật và Sư phạm. Ngoài việc cấp bằng, Trường Đại học Sài Gòn được Bộ Giáo dục và Đào tạo cho phép đào tạo cấp các chứng chỉ Bồi dưỡng nghiệp vụ sư phạm cho giảng viên đại học, cao đẳng và bồi dưỡng nghiệp vụ sư phạm cho giáo viên Tiếng Anh Tiểu học, chứng chỉ Công nghệ Thông tin và chứng chỉ Tiếng Anh theo khung năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam. Ngày 13/5/2017, Trường Đại học Sài Gòn được Chứng nhận kiểm định chất lượng giáo dục trường đại học. Năm 2018, Trường đón nhận Huân chương Lao động Hạng Ba do Chủ tịch nước Cộng hòa Xã hội Chủ nghĩa Việt Nam trao tặng.'})

MERGE (regularProgram:Program {name: 'Hệ chính quy', description: 'Chương trình đào tạo chính quy tại Trường Đại học Sài Gòn.'})
MERGE (undergraduateProgram:Program {name: 'Trình độ Đại học', description: 'Chương trình đào tạo trình độ đại học.'})
MERGE (highQualityProgram:Program {name: 'Chương trình chất lượng cao', description: 'Chương trình đào tạo chất lượng cao tại Trường Đại học Sài Gòn.'})
MERGE (postgraduateProgram:Program {name: 'Trình độ Sau Đại học', description: 'Chương trình đào tạo trình độ sau đại học.'})
MERGE (doctoralProgram:Program {name: 'Trình độ Tiến sĩ', description: 'Chương trình đào tạo trình độ tiến sĩ.'})
MERGE (continuingEducation:Program {name: 'Giáo dục thường xuyên', description: 'Chương trình giáo dục thường xuyên dành cho người học vừa làm vừa học.'})

WITH university, regularProgram, undergraduateProgram, highQualityProgram, postgraduateProgram, doctoralProgram, continuingEducation

MERGE (university)-[:offersProgram]->(regularProgram)
MERGE (regularProgram)-[:offersProgram]->(undergraduateProgram)
MERGE (regularProgram)-[:offersProgram]->(highQualityProgram)
MERGE (university)-[:offersProgram]->(postgraduateProgram)
MERGE (university)-[:offersProgram]->(doctoralProgram)
MERGE (university)-[:offersProgram]->(continuingEducation)

MERGE (undergraduateProgram)-[:offersProgram]->(program1:Program {name: 'Chương trình đại trà', description: 'Chương trình đại trà cho các ngành đào tạo đại học.'})
MERGE (program1)-[:offersProgram]->(programDetail1:Program {name: 'Giáo dục Chính trị - Du lịch', description: 'Chương trình đào tạo ngành Giáo dục Chính trị - Du lịch.'})
MERGE (program1)-[:offersProgram]->(programDetail2:Program {name: 'Giáo dục Mầm non - Kế toán', description: 'Chương trình đào tạo ngành Giáo dục Mầm non - Kế toán.'})
MERGE (program1)-[:offersProgram]->(programDetail3:Program {name: 'Giáo dục Tiểu học - Khoa học Môi trường', description: 'Chương trình đào tạo ngành Giáo dục Tiểu học - Khoa học Môi trường.'})
MERGE (program1)-[:offersProgram]->(programDetail4:Program {name: 'Sư phạm Âm nhạc - Kinh doanh Quốc tế', description: 'Chương trình đào tạo ngành Sư phạm Âm nhạc - Kinh doanh Quốc tế.'})
MERGE (program1)-[:offersProgram]->(programDetail5:Program {name: 'Sư phạm Địa lý - Kỹ thuật Điện', description: 'Chương trình đào tạo ngành Sư phạm Địa lý - Kỹ thuật Điện.'})
MERGE (program1)-[:offersProgram]->(programDetail6:Program {name: 'Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông', description: 'Chương trình đào tạo ngành Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông.'})
MERGE (program1)-[:offersProgram]->(programDetail7:Program {name: 'Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm', description: 'Chương trình đào tạo ngành Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm.'})
MERGE (program1)-[:offersProgram]->(programDetail8:Program {name: 'Sư phạm Lịch sử - Luật', description: 'Chương trình đào tạo ngành Sư phạm Lịch sử - Luật.'})
MERGE (program1)-[:offersProgram]->(programDetail9:Program {name: 'Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh', description: 'Chương trình đào tạo ngành Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh.'})
MERGE (program1)-[:offersProgram]->(programDetail10:Program {name: 'Sư phạm Mỹ thuật - Quản lý Giáo dục', description: 'Chương trình đào tạo ngành Sư phạm Mỹ thuật - Quản lý Giáo dục.'})
MERGE (program1)-[:offersProgram]->(programDetail11:Program {name: 'Sư phạm Ngữ Văn - Quản trị Kinh doanh', description: 'Chương trình đào tạo ngành Sư phạm Ngữ Văn - Quản trị Kinh doanh.'})
MERGE (program1)-[:offersProgram]->(programDetail12:Program {name: 'Sư phạm Sinh học - Quản trị Văn phòng', description: 'Chương trình đào tạo ngành Sư phạm Sinh học - Quản trị Văn phòng.'})
MERGE (program1)-[:offersProgram]->(programDetail13:Program {name: 'Sư phạm Tiếng Anh - Quốc tế học', description: 'Chương trình đào tạo ngành Sư phạm Tiếng Anh - Quốc tế học.'})
MERGE (program1)-[:offersProgram]->(programDetail14:Program {name: 'Sư phạm Toán học - Tài chính - Ngân hàng', description: 'Chương trình đào tạo ngành Sư phạm Toán học - Tài chính - Ngân hàng.'})
MERGE (program1)-[:offersProgram]->(programDetail15:Program {name: 'Sư phạm Vật lý - Tâm lý học', description: 'Chương trình đào tạo ngành Sư phạm Vật lý - Tâm lý học.'})
MERGE (program1)-[:offersProgram]->(programDetail16:Program {name: 'CNKT Điện tử - Viễn thông - Thanh nhạc', description: 'Chương trình đào tạo ngành CNKT Điện tử - Viễn thông - Thanh nhạc.'})
MERGE (program1)-[:offersProgram]->(programDetail17:Program {name: 'CNKT Điện, Điện tử - Thông tin - Thư viện', description: 'Chương trình đào tạo ngành CNKT Điện, Điện tử - Thông tin - Thư viện.'})
MERGE (program1)-[:offersProgram]->(programDetail18:Program {name: 'Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng', description: 'Chương trình đào tạo ngành Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng.'})
MERGE (program1)-[:offersProgram]->(programDetail19:Program {name: 'Công nghệ Thông tin - Việt Nam học', description: 'Chương trình đào tạo ngành Công nghệ Thông tin - Việt Nam học.'})

MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail1:Program {name: 'Hóa hữu cơ - Quản trị Kinh doanh', description: 'Chương trình đào tạo ngành Hóa hữu cơ - Quản trị Kinh doanh.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail2:Program {name: 'Hóa lý thuyết và Hóa lý - Tài chính – Ngân hàng', description: 'Chương trình đào tạo ngành Hóa lý thuyết và Hóa lý - Tài chính – Ngân hàng.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail3:Program {name: 'Khoa học Máy tính - Toán Giải tích', description: 'Chương trình đào tạo ngành Khoa học Máy tính - Toán Giải tích.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail4:Program {name: 'Lịch sử Việt Nam - Văn học Việt Nam', description: 'Chương trình đào tạo ngành Lịch sử Việt Nam - Văn học Việt Nam.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail5:Program {name: 'LL & PPDH bộ môn Toán - Luật dân sự và tố tụng dân sự', description: 'Chương trình đào tạo ngành LL & PPDH bộ môn Toán - Luật dân sự và tố tụng dân sự.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail6:Program {name: 'Ngôn ngữ học', description: 'Chương trình đào tạo ngành Ngôn ngữ học.'})
MERGE (postgraduateProgram)-[:offersProgram]->(postgraduateDetail7:Program {name: 'Quản lý Giáo dục', description: 'Chương trình đào tạo ngành Quản lý Giáo dục.'})

MERGE (doctoralProgram)-[:offersProgram]->(doctoralDetail1:Program {name: 'Hóa hữu cơ', description: 'Chương trình đào tạo ngành Hóa hữu cơ.'})
MERGE (doctoralProgram)-[:offersProgram]->(doctoralDetail2:Program {name: 'Lịch sử Việt Nam', description: 'Chương trình đào tạo ngành Lịch sử Việt Nam.'})
MERGE (doctoralProgram)-[:offersProgram]->(doctoralDetail3:Program {name: 'Quản lý Giáo dục', description: 'Chương trình đào tạo ngành Quản lý Giáo dục.'})
MERGE (doctoralProgram)-[:offersProgram]->(doctoralDetail4:Program {name: 'Toán Giải tích', description: 'Chương trình đào tạo ngành Toán Giải tích.'})
MERGE (doctoralProgram)-[:offersProgram]->(doctoralDetail5:Program {name: 'Quản trị Kinh doanh', description: 'Chương trình đào tạo ngành Quản trị Kinh doanh.'})

MERGE (continuingEducation)-[:offersProgram]->(continuingDetail1:Program {name: 'Đào tạo Đại học liên thông', description: 'Đào tạo liên thông các ngành Công nghệ Thông tin, Kế toán, Quản trị Kinh doanh, Giáo dục Mầm non và Giáo dục Tiểu học.'})
MERGE (continuingEducation)-[:offersProgram]->(continuingDetail2:Program {name: 'Đào tạo văn bằng thứ hai', description: 'Đào tạo văn bằng thứ hai trình độ đại học các ngành: Ngôn ngữ Anh, Kế toán, Luật, Quản trị Kinh doanh, Ngôn ngữ Anh, Giáo dục Tiểu học và Quản lý Giáo dục.'})
MERGE (continuingEducation)-[:offersProgram]->(continuingDetail3:Program {name: 'Đào tạo hệ đại học vừa làm vừa học', description: 'Đào tạo hệ đại học vừa làm vừa học (VLVH) các ngành Quản trị Kinh doanh, Tài chính - Ngân hàng, Tài chính - Kế toán, Luật, Giáo dục Tiểu học, Giáo dục Mầm non.'})