MERGE (university:Truong_Dai_hoc {name: "Trường Đại học Sài Gòn", description: "Trường Đại học Sài Gòn là cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh"})

// Ban lãnh đạo
MERGE (leadership1:Ban_lanh_dao {name: "Đảng ủy", description: "Ban lãnh đạo Đảng ủy trường Đại học Sài Gòn"})
MERGE (leadership2:Ban_lanh_dao {name: "Hiệu trưởng", description: "Ban lãnh đạo Hiệu trưởng trường Đại học Sài Gòn"})
MERGE (leadership3:Ban_lanh_dao {name: "Phó Hiệu trưởng", description: "Ban lãnh đạo các Phó Hiệu trưởng trường Đại học Sài Gòn"})
MERGE (leadership4:Ban_lanh_dao {name: "Hội đồng trường", description: "Ban lãnh đạo Hội đồng trường Đại học Sài Gòn"})

// Tổ chức đoàn thể
MERGE (org1:To_chuc_doan_the {name: "Công đoàn", description: "Tổ chức Công đoàn trường Đại học Sài Gòn"})
MERGE (org2:To_chuc_doan_the {name: "Đoàn Thanh niên", description: "Tổ chức Đoàn Thanh niên trường Đại học Sài Gòn"})
MERGE (org3:To_chuc_doan_the {name: "Hội Sinh viên", description: "Tổ chức Hội Sinh viên trường Đại học Sài Gòn"})

// Phòng ban chức năng
MERGE (dept1:Phong_ban {name: "Đào tạo", description: "Phòng Đào tạo trường Đại học Sài Gòn"})
MERGE (dept2:Phong_ban {name: "Tổ chức - Cán bộ", description: "Phòng Tổ chức - Cán bộ trường Đại học Sài Gòn"})
MERGE (dept3:Phong_ban {name: "Văn phòng", description: "Phòng Văn phòng trường Đại học Sài Gòn"})
MERGE (dept4:Phong_ban {name: "Kế hoạch - Tài chính", description: "Phòng Kế hoạch - Tài chính trường Đại học Sài Gòn"})
MERGE (dept5:Phong_ban {name: "Công tác sinh viên", description: "Phòng Công tác sinh viên trường Đại học Sài Gòn"})
MERGE (dept6:Phong_ban {name: "Quản lý khoa học", description: "Phòng Quản lý khoa học trường Đại học Sài Gòn"})
MERGE (dept7:Phong_ban {name: "Đào tạo sau đại học", description: "Phòng Đào tạo sau đại học trường Đại học Sài Gòn"})
MERGE (dept8:Phong_ban {name: "Thanh tra - Pháp chế", description: "Phòng Thanh tra - Pháp chế trường Đại học Sài Gòn"})
MERGE (dept9:Phong_ban {name: "Khảo thí & Đảm bảo chất lượng", description: "Phòng Khảo thí & Đảm bảo chất lượng trường Đại học Sài Gòn"})
MERGE (dept10:Phong_ban {name: "Ban Quản lý Dự án & Xây dựng", description: "Phòng Ban Quản lý Dự án & Xây dựng trường Đại học Sài Gòn"})
MERGE (dept11:Phong_ban {name: "Hợp tác quốc tế & Doanh nghiệp", description: "Phòng Hợp tác quốc tế & Doanh nghiệp trường Đại học Sài Gòn"})
MERGE (dept12:Phong_ban {name: "Thiết bị", description: "Phòng Thiết bị trường Đại học Sài Gòn"})
MERGE (dept13:Phong_ban {name: "Giáo dục thường xuyên", description: "Phòng Giáo dục thường xuyên trường Đại học Sài Gòn"})

// Các trung tâm trực thuộc
MERGE (center1:Trung_tam {name: "Khảo thí", description: "Trung tâm Khảo thí trường Đại học Sài Gòn"})
MERGE (center2:Trung_tam {name: "Đào tạo quốc tế", description: "Trung tâm Đào tạo quốc tế trường Đại học Sài Gòn"})
MERGE (center3:Trung_tam {name: "Hỗ trợ sinh viên", description: "Trung tâm Hỗ trợ sinh viên trường Đại học Sài Gòn"})
MERGE (center4:Trung_tam {name: "Học liệu", description: "Trung tâm Học liệu trường Đại học Sài Gòn"})
MERGE (center5:Trung_tam {name: "Công nghệ thông tin", description: "Trung tâm Công nghệ thông tin trường Đại học Sài Gòn"})
MERGE (center6:Trung_tam {name: "Ngoại ngữ", description: "Trung tâm Ngoại ngữ trường Đại học Sài Gòn"})
MERGE (center7:Trung_tam {name: "Tuyển sinh & Truyền thông", description: "Trung tâm Tuyển sinh & Truyền thông trường Đại học Sài Gòn"})
MERGE (center8:Trung_tam {name: "Ký túc xá", description: "Trung tâm Ký túc xá trường Đại học Sài Gòn"})
MERGE (center9:Trung_tam {name: "Trạm Y tế", description: "Trung tâm Trạm Y tế trường Đại học Sài Gòn"})

// Các khoa chuyên môn
MERGE (faculty1:Khoa {name: "Giáo dục Mầm non", description: "Khoa Giáo dục Mầm non trường Đại học Sài Gòn"})
MERGE (faculty2:Khoa {name: "Giáo dục Tiểu học", description: "Khoa Giáo dục Tiểu học trường Đại học Sài Gòn"})
MERGE (faculty3:Khoa {name: "Sư phạm Khoa học Xã hội", description: "Khoa Sư phạm Khoa học Xã hội trường Đại học Sài Gòn"})
MERGE (faculty4:Khoa {name: "Sư phạm Khoa học Tự nhiên", description: "Khoa Sư phạm Khoa học Tự nhiên trường Đại học Sài Gòn"})
MERGE (faculty5:Khoa {name: "Giáo dục", description: "Khoa Giáo dục trường Đại học Sài Gòn"})
MERGE (faculty6:Khoa {name: "Nghệ thuật", description: "Khoa Nghệ thuật trường Đại học Sài Gòn"})
MERGE (faculty7:Khoa {name: "Ngoại ngữ", description: "Khoa Ngoại ngữ trường Đại học Sài Gòn"})
MERGE (faculty8:Khoa {name: "Thư viện - Văn phòng", description: "Khoa Thư viện - Văn phòng trường Đại học Sài Gòn"})
MERGE (faculty9:Khoa {name: "Khoa học Môi trường", description: "Khoa Khoa học Môi trường trường Đại học Sài Gòn"})
MERGE (faculty10:Khoa {name: "Công nghệ Thông tin", description: "Khoa Công nghệ Thông tin trường Đại học Sài Gòn"})
MERGE (faculty11:Khoa {name: "Quản trị Kinh doanh", description: "Khoa Quản trị Kinh doanh trường Đại học Sài Gòn"})
MERGE (faculty12:Khoa {name: "Tài chính - Kế toán", description: "Khoa Tài chính - Kế toán trường Đại học Sài Gòn"})
MERGE (faculty13:Khoa {name: "Văn hóa và Du lịch", description: "Khoa Văn hóa và Du lịch trường Đại học Sài Gòn"})
MERGE (faculty14:Khoa {name: "Khoa học Chính trị", description: "Khoa Khoa học Chính trị trường Đại học Sài Gòn"})
MERGE (faculty15:Khoa {name: "Toán - Ứng dụng", description: "Khoa Toán - Ứng dụng trường Đại học Sài Gòn"})
MERGE (faculty16:Khoa {name: "Điện tử - Viễn thông", description: "Khoa Điện tử - Viễn thông trường Đại học Sài Gòn"})
MERGE (faculty17:Khoa {name: "Giáo dục Quốc phòng & An ninh - Giáo dục Thể chất", description: "Khoa Giáo dục Quốc phòng & An ninh - Giáo dục Thể chất trường Đại học Sài Gòn"})

// Đơn vị trực thuộc
MERGE (unit1:Don_vi {name: "Viện Khoa học Dữ liệu và Trí tuệ nhân tạo", description: "Viện Khoa học Dữ liệu và Trí tuệ nhân tạo trường Đại học Sài Gòn"})
MERGE (unit2:Don_vi {name: "Viện Nghiên cứu Môi trường - Sức khỏe", description: "Viện Nghiên cứu Môi trường - Sức khỏe trường Đại học Sài Gòn"})
MERGE (unit3:Don_vi {name: "Trung tâm Thực hành Sư phạm", description: "Trung tâm Thực hành Sư phạm trường Đại học Sài Gòn"})
MERGE (unit4:Don_vi {name: "Trung học Thực hành Sài Gòn", description: "Trung học Thực hành Sài Gòn trường Đại học Sài Gòn"})
MERGE (unit5:Don_vi {name: "Tiểu học Thực hành Sài Gòn", description: "Tiểu học Thực hành Sài Gòn trường Đại học Sài Gòn"})

// Tạo quan hệ
MERGE (university)-[:has_leadership]->(leadership1)
MERGE (university)-[:has_leadership]->(leadership2)
MERGE (university)-[:has_leadership]->(leadership3)
MERGE (university)-[:has_leadership]->(leadership4)

MERGE (university)-[:has_organization]->(org1)
MERGE (university)-[:has_organization]->(org2)
MERGE (university)-[:has_organization]->(org3)

MERGE (university)-[:has_department]->(dept1)
MERGE (university)-[:has_department]->(dept2)
MERGE (university)-[:has_department]->(dept3)
MERGE (university)-[:has_department]->(dept4)
MERGE (university)-[:has_department]->(dept5)
MERGE (university)-[:has_department]->(dept6)
MERGE (university)-[:has_department]->(dept7)
MERGE (university)-[:has_department]->(dept8)
MERGE (university)-[:has_department]->(dept9)
MERGE (university)-[:has_department]->(dept10)
MERGE (university)-[:has_department]->(dept11)
MERGE (university)-[:has_department]->(dept12)
MERGE (university)-[:has_department]->(dept13)

MERGE (university)-[:has_center]->(center1)
MERGE (university)-[:has_center]->(center2)
MERGE (university)-[:has_center]->(center3)
MERGE (university)-[:has_center]->(center4)
MERGE (university)-[:has_center]->(center5)
MERGE (university)-[:has_center]->(center6)
MERGE (university)-[:has_center]->(center7)
MERGE (university)-[:has_center]->(center8)
MERGE (university)-[:has_center]->(center9)

MERGE (university)-[:has_faculty]->(faculty1)
MERGE (university)-[:has_faculty]->(faculty2)
MERGE (university)-[:has_faculty]->(faculty3)
MERGE (university)-[:has_faculty]->(faculty4)
MERGE (university)-[:has_faculty]->(faculty5)
MERGE (university)-[:has_faculty]->(faculty6)
MERGE (university)-[:has_faculty]->(faculty7)
MERGE (university)-[:has_faculty]->(faculty8)
MERGE (university)-[:has_faculty]->(faculty9)
MERGE (university)-[:has_faculty]->(faculty10)
MERGE (university)-[:has_faculty]->(faculty11)
MERGE (university)-[:has_faculty]->(faculty12)
MERGE (university)-[:has_faculty]->(faculty13)
MERGE (university)-[:has_faculty]->(faculty14)
MERGE (university)-[:has_faculty]->(faculty15)
MERGE (university)-[:has_faculty]->(faculty16)
MERGE (university)-[:has_faculty]->(faculty17)

MERGE (university)-[:has_unit]->(unit1)
MERGE (university)-[:has_unit]->(unit2)
MERGE (university)-[:has_unit]->(unit3)
MERGE (university)-[:has_unit]->(unit4)
MERGE (university)-[:has_unit]->(unit5)