MERGE (university:Truong_Dai_hoc {name: "Trường Đại học Sài Gòn", description: "Trường Đại học Sài Gòn là cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh"})

// Các trình độ đào tạo
MERGE (degree1:Degree {name: "Đại học", description: "Trình độ đào tạo đại học hệ chính quy"})
MERGE (degree2:Degree {name: "Sau đại học", description: "Trình độ đào tạo thạc sĩ"}) 
MERGE (degree3:Degree {name: "Tiến sĩ", description: "Trình độ đào tạo tiến sĩ"})

// Các chương trình đào tạo
MERGE (program1:Program {name: "Chính quy đại trà", description: "Chương trình đào tạo chính quy đại trà"})
MERGE (program2:Program {name: "Chất lượng cao", description: "Chương trình đào tạo chất lượng cao"})
MERGE (program3:Program {name: "Giáo dục thường xuyên", description: "Chương trình giáo dục thường xuyên gồm vừa làm vừa học, liên thông, bằng hai"})

// Các ngành đào tạo đại học đại trà
MERGE (major1:Nganh_dao_tao {name: "Giáo dục Chính trị - Du lịch", description: "Ngành Giáo dục Chính trị - Du lịch hệ đại học chính quy"})
MERGE (major2:Nganh_dao_tao {name: "Giáo dục Mầm non - Kế toán", description: "Ngành Giáo dục Mầm non - Kế toán hệ đại học chính quy"})
MERGE (major3:Nganh_dao_tao {name: "Giáo dục Tiểu học - Khoa học Môi trường", description: "Ngành Giáo dục Tiểu học - Khoa học Môi trường hệ đại học chính quy"})
MERGE (major4:Nganh_dao_tao {name: "Sư phạm Âm nhạc - Kinh doanh Quốc tế", description: "Ngành Sư phạm Âm nhạc - Kinh doanh Quốc tế hệ đại học chính quy"})
MERGE (major5:Nganh_dao_tao {name: "Sư phạm Địa lý - Kỹ thuật Điện", description: "Ngành Sư phạm Địa lý - Kỹ thuật Điện hệ đại học chính quy"})
MERGE (major6:Nganh_dao_tao {name: "Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông", description: "Ngành Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông hệ đại học chính quy"})
MERGE (major7:Nganh_dao_tao {name: "Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm", description: "Ngành Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm hệ đại học chính quy"})
MERGE (major8:Nganh_dao_tao {name: "Sư phạm Lịch sử - Luật", description: "Ngành Sư phạm Lịch sử - Luật hệ đại học chính quy"})
MERGE (major9:Nganh_dao_tao {name: "Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh", description: "Ngành Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh hệ đại học chính quy"})
MERGE (major10:Nganh_dao_tao {name: "Sư phạm Mỹ thuật - Quản lý Giáo dục", description: "Ngành Sư phạm Mỹ thuật - Quản lý Giáo dục hệ đại học chính quy"})
MERGE (major11:Nganh_dao_tao {name: "Sư phạm Ngữ Văn - Quản trị Kinh doanh", description: "Ngành Sư phạm Ngữ Văn - Quản trị Kinh doanh hệ đại học chính quy"})
MERGE (major12:Nganh_dao_tao {name: "Sư phạm Sinh học - Quản trị Văn phòng", description: "Ngành Sư phạm Sinh học - Quản trị Văn phòng hệ đại học chính quy"})
MERGE (major13:Nganh_dao_tao {name: "Sư phạm Tiếng Anh - Quốc tế học", description: "Ngành Sư phạm Tiếng Anh - Quốc tế học hệ đại học chính quy"})
MERGE (major14:Nganh_dao_tao {name: "Sư phạm Toán học - Tài chính - Ngân hàng", description: "Ngành Sư phạm Toán học - Tài chính - Ngân hàng hệ đại học chính quy"})
MERGE (major15:Nganh_dao_tao {name: "Sư phạm Vật lý - Tâm lý học", description: "Ngành Sư phạm Vật lý - Tâm lý học hệ đại học chính quy"})
MERGE (major16:Nganh_dao_tao {name: "CNKT Điện tử - Viễn thông - Thanh nhạc", description: "Ngành CNKT Điện tử - Viễn thông - Thanh nhạc hệ đại học chính quy"})
MERGE (major17:Nganh_dao_tao {name: "CNKT Điện, Điện tử - Thông tin - Thư viện", description: "Ngành CNKT Điện, Điện tử - Thông tin - Thư viện hệ đại học chính quy"})
MERGE (major18:Nganh_dao_tao {name: "Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng", description: "Ngành Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng hệ đại học chính quy"})
MERGE (major19:Nganh_dao_tao {name: "Công nghệ Thông tin - Việt Nam học", description: "Ngành Công nghệ Thông tin - Việt Nam học hệ đại học chính quy"})

// Ngành đào tạo chất lượng cao
MERGE (major20:Nganh_dao_tao {name: "Công nghệ Thông tin chất lượng cao", description: "Ngành Công nghệ Thông tin chương trình chất lượng cao"})

// Các ngành sau đại học
MERGE (major21:Nganh_dao_tao {name: "Hóa hữu cơ", description: "Ngành Hóa hữu cơ trình độ thạc sĩ"})
MERGE (major22:Nganh_dao_tao {name: "Quản trị Kinh doanh", description: "Ngành Quản trị Kinh doanh trình độ thạc sĩ"})
MERGE (major23:Nganh_dao_tao {name: "Hóa lý thuyết và Hóa lý", description: "Ngành Hóa lý thuyết và Hóa lý trình độ thạc sĩ"})
MERGE (major24:Nganh_dao_tao {name: "Tài chính – Ngân hàng", description: "Ngành Tài chính – Ngân hàng trình độ thạc sĩ"})
MERGE (major25:Nganh_dao_tao {name: "Khoa học Máy tính", description: "Ngành Khoa học Máy tính trình độ thạc sĩ"})
MERGE (major26:Nganh_dao_tao {name: "Toán Giải tích", description: "Ngành Toán Giải tích trình độ thạc sĩ"})
MERGE (major27:Nganh_dao_tao {name: "Lịch sử Việt Nam", description: "Ngành Lịch sử Việt Nam trình độ thạc sĩ"})
MERGE (major28:Nganh_dao_tao {name: "Văn học Việt Nam", description: "Ngành Văn học Việt Nam trình độ thạc sĩ"})
MERGE (major29:Nganh_dao_tao {name: "LL & PPDH bộ môn Toán", description: "Ngành LL & PPDH bộ môn Toán trình độ thạc sĩ"})
MERGE (major30:Nganh_dao_tao {name: "Luật dân sự và tố tụng dân sự", description: "Ngành Luật dân sự và tố tụng dân sự trình độ thạc sĩ"})
MERGE (major31:Nganh_dao_tao {name: "Ngôn ngữ học", description: "Ngành Ngôn ngữ học trình độ thạc sĩ"})
MERGE (major32:Nganh_dao_tao {name: "Quản lý Giáo dục", description: "Ngành Quản lý Giáo dục trình độ thạc sĩ"})

// Các ngành tiến sĩ
MERGE (major33:Nganh_dao_tao {name: "Hóa hữu cơ", description: "Ngành Hóa hữu cơ trình độ tiến sĩ"})
MERGE (major34:Nganh_dao_tao {name: "Lịch sử Việt Nam", description: "Ngành Lịch sử Việt Nam trình độ tiến sĩ"})
MERGE (major35:Nganh_dao_tao {name: "Quản lý Giáo dục", description: "Ngành Quản lý Giáo dục trình độ tiến sĩ"})
MERGE (major36:Nganh_dao_tao {name: "Toán Giải tích", description: "Ngành Toán Giải tích trình độ tiến sĩ"})
MERGE (major37:Nganh_dao_tao {name: "Quản trị Kinh doanh", description: "Ngành Quản trị Kinh doanh trình độ tiến sĩ"})

// Các ngành giáo dục thường xuyên
MERGE (major38:Nganh_dao_tao {name: "Công nghệ Thông tin liên thông", description: "Ngành Công nghệ Thông tin hệ liên thông"})
MERGE (major39:Nganh_dao_tao {name: "Kế toán liên thông", description: "Ngành Kế toán hệ liên thông"})
MERGE (major40:Nganh_dao_tao {name: "Quản trị Kinh doanh liên thông", description: "Ngành Quản trị Kinh doanh hệ liên thông"})
MERGE (major41:Nganh_dao_tao {name: "Giáo dục Mầm non liên thông", description: "Ngành Giáo dục Mầm non hệ liên thông"})
MERGE (major42:Nganh_dao_tao {name: "Giáo dục Tiểu học liên thông", description: "Ngành Giáo dục Tiểu học hệ liên thông"})
MERGE (major43:Nganh_dao_tao {name: "Ngôn ngữ Anh bằng hai", description: "Ngành Ngôn ngữ Anh văn bằng hai"})
MERGE (major44:Nganh_dao_tao {name: "Kế toán bằng hai", description: "Ngành Kế toán văn bằng hai"})
MERGE (major45:Nganh_dao_tao {name: "Luật bằng hai", description: "Ngành Luật văn bằng hai"})
MERGE (major46:Nganh_dao_tao {name: "Quản trị Kinh doanh bằng hai", description: "Ngành Quản trị Kinh doanh văn bằng hai"})
MERGE (major47:Nganh_dao_tao {name: "Giáo dục Tiểu học bằng hai", description: "Ngành Giáo dục Tiểu học văn bằng hai"})
MERGE (major48:Nganh_dao_tao {name: "Quản lý Giáo dục bằng hai", description: "Ngành Quản lý Giáo dục văn bằng hai"})
MERGE (major49:Nganh_dao_tao {name: "Quản trị Kinh doanh VLVH", description: "Ngành Quản trị Kinh doanh hệ vừa làm vừa học"})
MERGE (major50:Nganh_dao_tao {name: "Tài chính - Ngân hàng VLVH", description: "Ngành Tài chính - Ngân hàng hệ vừa làm vừa học"})
MERGE (major51:Nganh_dao_tao {name: "Tài chính - Kế toán VLVH", description: "Ngành Tài chính - Kế toán hệ vừa làm vừa học"})
MERGE (major52:Nganh_dao_tao {name: "Luật VLVH", description: "Ngành Luật hệ vừa làm vừa học"})
MERGE (major53:Nganh_dao_tao {name: "Giáo dục Tiểu học VLVH", description: "Ngành Giáo dục Tiểu học hệ vừa làm vừa học"})
MERGE (major54:Nganh_dao_tao {name: "Giáo dục Mầm non VLVH", description: "Ngành Giáo dục Mầm non hệ vừa làm vừa học"})

// Cơ sở vật chất
MERGE (facility1:Co_so {name: "273 An Dương Vương", description: "Cơ sở 273 An Dương Vương, Q.5 với diện tích 42.743 m2"})
MERGE (facility2:Co_so {name: "105 Bà Huyện Thanh Quan", description: "Cơ sở 105 Bà Huyện Thanh Quan, Q.3 với diện tích 4.823 m2"})
MERGE (facility3:Co_so {name: "04 Tôn Đức Thắng", description: "Cơ sở 04 Tôn Đức Thắng, Q.1 với diện tích 19.655 m2"})
MERGE (facility4:Co_so {name: "Ký túc xá 99 An Dương Vương", description: "Ký túc xá 99 An Dương Vương, Q.8 với diện tích 4.800 m2"})

// Tạo quan hệ
MERGE (university)-[:has_degree]->(degree1)
MERGE (university)-[:has_degree]->(degree2)
MERGE (university)-[:has_degree]->(degree3)

MERGE (university)-[:offers_program]->(program1)
MERGE (university)-[:offers_program]->(program2)
MERGE (university)-[:offers_program]->(program3)

// Quan hệ ngành đào tạo đại học đại trà
MERGE (program1)-[:includes_major]->(major1)
MERGE (program1)-[:includes_major]->(major2)
MERGE (program1)-[:includes_major]->(major3)
MERGE (program1)-[:includes_major]->(major4)
MERGE (program1)-[:includes_major]->(major5)
MERGE (program1)-[:includes_major]->(major6)
MERGE (program1)-[:includes_major]->(major7)
MERGE (program1)-[:includes_major]->(major8)
MERGE (program1)-[:includes_major]->(major9)
MERGE (program1)-[:includes_major]->(major10)
MERGE (program1)-[:includes_major]->(major11)
MERGE (program1)-[:includes_major]->(major12)
MERGE (program1)-[:includes_major]->(major13)
MERGE (program1)-[:includes_major]->(major14)
MERGE (program1)-[:includes_major]->(major15)
MERGE (program1)-[:includes_major]->(major16)
MERGE (program1)-[:includes_major]->(major17)
MERGE (program1)-[:includes_major]->(major18)
MERGE (program1)-[:includes_major]->(major19)

// Quan hệ ngành chất lượng cao
MERGE (program2)-[:includes_major]->(major20)

// Quan hệ ngành sau đại học
MERGE (degree2)-[:has_major]->(major21)
MERGE (degree2)-[:has_major]->(major22)
MERGE (degree2)-[:has_major]->(major23)
MERGE (degree2)-[:has_major]->(major24)
MERGE (degree2)-[:has_major]->(major25)
MERGE (degree2)-[:has_major]->(major26)
MERGE (degree2)-[:has_major]->(major27)
MERGE (degree2)-[:has_major]->(major28)
MERGE (degree2)-[:has_major]->(major29)
MERGE (degree2)-[:has_major]->(major30)
MERGE (degree2)-[:has_major]->(major31)
MERGE (degree2)-[:has_major]->(major32)

// Quan hệ ngành tiến sĩ
MERGE (degree3)-[:has_major]->(major33)
MERGE (degree3)-[:has_major]->(major34)
MERGE (degree3)-[:has_major]->(major35)
MERGE (degree3)-[:has_major]->(major36)
MERGE (degree3)-[:has_major]->(major37)

// Quan hệ ngành giáo dục thường xuyên
MERGE (program3)-[:includes_major]->(major38)
MERGE (program3)-[:includes_major]->(major39)
MERGE (program3)-[:includes_major]->(major40)
MERGE (program3)-[:includes_major]->(major41)
MERGE (program3)-[:includes_major]->(major42)
MERGE (program3)-[:includes_major]->(major43)
MERGE (program3)-[:includes_major]->(major44)
MERGE (program3)-[:includes_major]->(major45)
MERGE (program3)-[:includes_major]->(major46)
MERGE (program3)-[:includes_major]->(major47)
MERGE (program3)-[:includes_major]->(major48)
MERGE (program3)-[:includes_major]->(major49)
MERGE (program3)-[:includes_major]->(major50)
MERGE (program3)-[:includes_major]->(major51)
MERGE (program3)-[:includes_major]->(major52)
MERGE (program3)-[:includes_major]->(major53)
MERGE (program3)-[:includes_major]->(major54)

// Quan hệ cơ sở vật chất
MERGE (university)-[:has_facility]->(facility1)
MERGE (university)-[:has_facility]->(facility2)
MERGE (university)-[:has_facility]->(facility3)
MERGE (university)-[:has_facility]->(facility4)