MERGE (university:University {name: 'Trường Đại học Sài Gòn', description: 'Trường Đại học Sài Gòn là cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, chịu sự quản lý nhà nước về giáo dục của Bộ Giáo dục và Đào tạo; là trường đại học đào tạo đa ngành, đa lĩnh vực. Trường Đại học Sài Gòn đào tạo từ trình độ đại học và sau đại học, theo 2 phương thức: chính quy và giáo dục thường xuyên (vừa làm vừa học, văn bằng hai, liên thông). Hiện nay, Trường đang tổ chức đào tạo 05 chuyên ngành tiến sĩ, 12 chuyên ngành cao học và 39 chương trình đào tạo trình độ đại học thuộc các lĩnh vực: Kinh tế - Kỹ thuật - Công nghệ, Văn hóa xã hội, chính trị, Nghệ thuật và Sư phạm. Ngoài việc cấp bằng, Trường Đại học Sài Gòn được Bộ Giáo dục và Đào tạo cho phép đào tạo cấp các chứng chỉ Bồi dưỡng nghiệp vụ sư phạm cho giảng viên đại học, cao đẳng và bồi dưỡng nghiệp vụ sư phạm cho giáo viên Tiếng Anh Tiểu học, chứng chỉ Công nghệ Thông tin và chứng chỉ Tiếng Anh theo khung năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam. Ngày 13/5/2017, Trường Đại học Sài Gòn được Chứng nhận kiểm định chất lượng giáo dục trường đại học. Năm 2018, Trường đón nhận Huân chương Lao động Hạng Ba do Chủ tịch nước Cộng hòa Xã hội Chủ nghĩa Việt Nam trao tặng.'})

MERGE (journal:Journal {name: 'Tạp chí Khoa học Đại học Sài Gòn', description: 'Tạp chí Khoa học Đại học Sài Gòn phục vụ cán bộ giảng dạy, nghiên cứu, quản lý, sinh viên các trường đại học, cao đẳng, các viện, học viện, các trung tâm nghiên cứu. Là diễn đàn khoa học công bố các kết quả nghiên cứu và hoạt động khoa học của cán bộ, giảng viên trường Đại học Sài Gòn.'})
MERGE (university)-[:publishesIn]->(journal)

MERGE (regulation:Research {name: 'Quy định chung về bài báo khoa học', description: 'Bài báo khoa học phải nêu rõ mục tiêu nghiên cứu, có kết quả mới, được phản biện và có danh mục chú thích và tài liệu tham khảo. Phải gồm đầy đủ các nội dung và tuân thủ thể lệ gửi bài.'})
MERGE (journal)-[:hasArticles]->(regulation)

MERGE (submissionGuidelines:Research {name: 'Thể lệ gửi bài đăng tạp chí', description: 'Bài gửi đăng trên Tạp chí phải là công trình khoa học, chưa từng công bố trong ấn phẩm khác, được viết bằng tiếng Việt hoặc tiếng Anh, không quá 12 trang A4, và tuân thủ các yêu cầu về cấu trúc và định dạng.'})
MERGE (journal)-[:hasArticles]->(submissionGuidelines)