MERGE (university:University {name: 'Trường Đại học Sài Gòn', description: 'Trường Đại học Sài Gòn là cơ sở giáo dục Đại học công lập trực thuộc UBND TP. Hồ Chí Minh, chịu sự quản lý nhà nước về giáo dục của Bộ Giáo dục và Đào tạo; là trường đại học đào tạo đa ngành, đa lĩnh vực. Trường Đại học Sài Gòn đào tạo từ trình độ đại học và sau đại học, theo 2 phương thức: chính quy và giáo dục thường xuyên (vừa làm vừa học, văn bằng hai, liên thông). Hiện nay, Trường đang tổ chức đào tạo 05 chuyên ngành tiến sĩ, 12 chuyên ngành cao học và 39 chương trình đào tạo trình độ đại học thuộc các lĩnh vực: Kinh tế - Kỹ thuật - Công nghệ, Văn hóa xã hội, chính trị, Nghệ thuật và Sư phạm. Ngoài việc cấp bằng, Trường Đại học Sài Gòn được Bộ Giáo dục và Đào tạo cho phép đào tạo cấp các chứng chỉ Bồi dưỡng nghiệp vụ sư phạm cho giảng viên đại học, cao đẳng và bồi dưỡng nghiệp vụ sư phạm cho giáo viên Tiếng Anh Tiểu học, chứng chỉ Công nghệ Thông tin và chứng chỉ Tiếng Anh theo khung năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam. Ngày 13/5/2017, Trường Đại học Sài Gòn được Chứng nhận kiểm định chất lượng giáo dục trường đại học. Năm 2018, Trường đón nhận Huân chương Lao động Hạng Ba do Chủ tịch nước Cộng hòa Xã hội Chủ nghĩa Việt Nam trao tặng.'})

MERGE (program1:Program {name: 'Chương trình đại trà', description: 'Chương trình đại trà tại Trường Đại học Sài Gòn bao gồm các ngành như Giáo dục Chính trị - Du lịch, Giáo dục Mầm non - Kế toán, Giáo dục Tiểu học - Khoa học Môi trường, Sư phạm Âm nhạc - Kinh doanh Quốc tế, Sư phạm Địa lý - Kỹ thuật Điện, Sư phạm Hóa học - Kỹ thuật Điện tử - Viễn thông, Sư phạm Khoa học Tự nhiên - Kỹ thuật Phần mềm, Sư phạm Lịch sử - Luật, Sư phạm Lịch sử - Địa lý - Ngôn ngữ Anh, Sư phạm Mỹ thuật - Quản lý Giáo dục, Sư phạm Ngữ Văn - Quản trị Kinh doanh, Sư phạm Sinh học - Quản trị Văn phòng, Sư phạm Tiếng Anh - Quốc tế học, Sư phạm Toán học - Tài chính - Ngân hàng, Sư phạm Vật lý - Tâm lý học, CNKT Điện tử - Viễn thông - Thanh nhạc, CNKT Điện, Điện tử - Thông tin - Thư viện, Công nghệ Kỹ thuật Môi trường - Toán Ứng dụng, Công nghệ Thông tin - Việt Nam học.'})
MERGE (university)-[:offersPrograms]->(program1)

MERGE (program2:Program {name: 'Chương trình chất lượng cao', description: 'Chương trình chất lượng cao tại Trường Đại học Sài Gòn chuyên ngành Công nghệ Thông tin.'})
MERGE (university)-[:offersPrograms]->(program2)

MERGE (postgraduateProgram:Program {name: 'Chương trình Sau Đại học', description: 'Chương trình Sau Đại học tại Trường Đại học Sài Gòn bao gồm các ngành như Hóa hữu cơ - Quản trị Kinh doanh, Hóa lý thuyết và Hóa lý - Tài chính – Ngân hàng, Khoa học Máy tính - Toán Giải tích, Lịch sử Việt Nam - Văn học Việt Nam, LL & PPDH bộ môn Toán - Luật dân sự và tố tụng dân sự, Ngôn ngữ học, Quản lý Giáo dục.'})
MERGE (university)-[:offersPrograms]->(postgraduateProgram)

MERGE (doctoralProgram:Program {name: 'Chương trình Tiến sĩ', description: 'Chương trình Tiến sĩ tại Trường Đại học Sài Gòn bao gồm các ngành như Hóa hữu cơ, Lịch sử Việt Nam, Quản lý Giáo dục, Toán Giải tích, Quản trị Kinh doanh.'})
MERGE (university)-[:offersPrograms]->(doctoralProgram)

MERGE (continuingEducation:Program {name: 'Giáo dục thường xuyên', description: 'Chương trình giáo dục thường xuyên tại Trường Đại học Sài Gòn bao gồm đào tạo Đại học liên thông các ngành Công nghệ Thông tin, Kế toán, Quản trị Kinh doanh, Giáo dục Mầm non và Giáo dục Tiểu học, đào tạo văn bằng thứ hai trình độ đại học các ngành: Ngôn ngữ Anh, Kế toán, Luật, Quản trị Kinh doanh, Ngôn ngữ Anh, Giáo dục Tiểu học và Quản lý Giáo dục, đào tạo hệ đại học vừa làm vừa học (VLVH) các ngành Quản trị Kinh doanh, Tài chính - Ngân hàng, Tài chính - Kế toán, Luật, Giáo dục Tiểu học, Giáo dục Mầm non.'})
MERGE (university)-[:offersPrograms]->(continuingEducation)

MERGE (facility:Department {name: 'Cơ sở vật chất', description: 'Trường Đại học Sài Gòn hiện có 03 cơ sở đào tạo Đại học và Sau Đại học cùng với Ký túc xá Sinh viên, với tổng diện tích gần 30 ha, bao gồm Cơ sở 273 An Dương Vương, Q.5 42.743 m2, Cơ sở 105 Bà Huyện Thanh Quan, Q.3 4.823 m2, Cơ sở 04 Tôn Đức Thắng, Q.1 19.655 m2, Ký túc xá 99 An Dương Vương, Q.8 4.800 m2.'})
MERGE (university)-[:hasDepartments]->(facility)